### ISSUE TITLE
Enhance plot_point_obs to color the points by message type and/or variable name.

### ISSUE THREAD

**Issue by davidfillmore** [dtcenter/MET#1052]
This request came up during the AF project.  Would like to enhance the plotting options for plot_point_obs.  See Jonathan Vigh who already did this using NCL and implement the options he chose.  One tricky part is adding a legend for this.
<br/>

<br/>
Consider supporting different colors and/or plotting symbols.
<br/>

<i>[MET-1052] created by johnhg</i>

**Comment by JohnHalleyGotway** [comment]
This request is handled by the plot_point_obs overhaul in #1528. Coloring the point observations based on the variable name or message type can be done in the new plot_point_obs configuration file.

**Comment by JohnHalleyGotway** [comment]
Resolved by PR #1560
