### ISSUE TITLE
MTD temporal convolution radius

### ISSUE THREAD

**Issue by rgbullock** [dtcenter/MET#1133]
Right now the MTD temporal convolution code is hardwired to a convolution radius of 1.  This needs to be generalized so the user can specify a different value

**Comment by JohnHalleyGotway** [comment]
This feature was requested by a user via MET-Help:
   https://rt.rap.ucar.edu/rt/Ticket/Display.html?id=88022

The temporal smoothing in MTD is hard-coded to be +/- 1 time step. This user would like to have the ability to apply no temporal smoothing in MTD to see how it changes the results.

More generally, recommend that the amount of temporal smoothing be a configurable item specified as a beginning and ending offset relative to the current time. For example, the default (existing) setting would be:
   conv_time_window = { beg = -1; end = 1; }

And for no temporal smoothing:
   conv_time_window = { beg = 0; end = 0; }

Or for the last 3 time steps:
   conv_time_window = { beg = -3; end = 0; }

**Comment by JohnHalleyGotway** [comment]
Finished adding config file option, updating the output columns, updating the user's guide, and adding a new unit test call to mtd to exercise this functionality.
