### ISSUE TITLE
MTD user-specified percentile output

### ISSUE THREAD

**Issue by rgbullock** [dtcenter/MET#1134]
Add percentiles (especially a user-chosen percentile) to the MTD text output.

**Comment by rgbullock** [comment]
Add percentiles for both 3D objects and 2D constant-time slices to ascii output.  Mimic the existing naming conventions of MODE and MTD.

**Comment by JohnHalleyGotway** [comment]
Randy contacted Jeff Duda to clarify this development issue on 1/2/2020.  Here is his response:

I requested that a custom percentile value be added to the output of MODE-TD, as is done in MODE. Such a custom percentile can be set in the config file. I specifically am going to want to output the 99th percentile value in my usage.

**Comment by JohnHalleyGotway** [comment]
Finished adding config file option, writing new output columns, updating the documentation, and making sure the unit test output looks sane.
