### ISSUE TITLE
Gaussian Filter Interpolation: Surrogate Severe

### ISSUE THREAD

**Issue by lindsayrblank** [dtcenter/MET#1136]
Goal: implement gaussian filter on surrogate severe data as an interpolation method.
Requestors: Burkely Gallo from NSSL and Mike Erickson from WPC. This issue is associated with issue #948. 

@hsoh-u and I met today to discuss how to implement this. 

First, there is some confusion over definitions. The following is a list of how we use certain terms and how Burkely and Mike use certain terms.
**Definitions**
1. sigma: 
    - DTC definition: the weight of the center point being interpolated
    - BG&ME definition: the radius of the Gaussian smoother
2. width:
    - DTC definition: the radius of the Gaussian smoother
    - BG&ME definition: the weight of the center point.

From here on out, I'll be using everything in terms of the DTC. 

**Steps/Components Required**:
1. User input: user provides a value for the width in km and for a truncation factor in the config file. The truncation factor is what defines the size of the filter grid (more that later).

2. Input data: as of right now, we are limiting this to a Lambert Conformal projection. Other projections will be implemented at future times.

3. Determine what dx/dy is: open the input data and extract the dx/dy values from it. This only needs to be done once. 

4. Calculate sigma: This is done through the following equation (width*truncation_factor)/dx = sigma. The truncation factor is what ensures that the filter grid will not be the same size or larger than the data grid. *Note* the sigma value will be rounded to the nearest whole number in order to complete step 5.

5. Calculate the size of the filter grid from sigma. For example, sigma = 5. Taking 1 center point, there must be 4 points to the left of it and 4 points to the right of it. The same must be true in the y direction. 4+4+1 = 9 so the filter is a 9x9 grid.

6. Apply this filter across all relevant grid points to get a Gaussian interpolated field. 

**Future Plans**
- First implementation is only Lambert Conformal projections (BG's data).
- Second implementation is lat/long coordinate system (ME's data)
- Third is all other possible projections.

**Comment by TaraJensen** [comment]
Work on support for lat/lon grid - Charge 277003

**Comment by lindsayrblank** [comment]
Surrogate Severe Process:
1. Input gridded model updraft helicity data.
2. Define an appropriate threshold that corresponds with the severe weather of interest (i.e. >=75m^2/s^2 Sobash et al. 2016).
3. Use this threshold to create a fine resolution binary grid by determining at each cell whether or not the UH exceeded the desired threshold.
4. Regrid this fine resolution binary grid to a coarser grid (in the literature, both the practically perfect and surrogate severe are regridded to the same dimension).
5. Smooth the new, coarser grid using the Gaussian interpolation method to produce a probability of occurrence at each point.

**Comment by hsoh-u** [comment]
[practically_perfectnc.f90.txt](https://github.com/NCAR/MET/files/4284263/practically_perfectnc.f90.txt)

**Comment by hsoh-u** [comment]
Finally we matched Berkeley's result by correcting testing procedures (we did an extra Gaussian filtering).
