### ISSUE TITLE
PB2NC bug in the hdr_vld array when computing time summaries.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1137]
Perry Shafran at NOAA/EMC uncovered a bug in pb2nc when computing time summaries for air quality data.  Here's the RT Ticket:
   https://rt.rap.ucar.edu/rt/Ticket/Display.html?id=89921

I copied sample data down to dakota to replicate this behavior.  Please look on dakota in:
   /d3/projects/MET/MET_Help/shafran_data_20190606

Run this pb2nc command:
   /d3/projects/MET/MET_releases/met-8.1/bin/pb2nc \
   prepda.2019060312 prepda.2019060312_debug.nc PB2NCConfig_aqmmax \
   -pbfile prepda.2019060212 -nmsg 10 -log run_pb2nc.log

And run these commands to see the contents of the "hdr_vld_table" and "hdr_vld" variables:

ncdump -v hdr_vld_table prepda.2019060312_debug.nc
    hdr_vld_table =
  "20190602_040000" ;

ncdump -v hdr_vld prepda.2019060312_debug.nc
 hdr_vld = 0, 2, 2, 2, 2, 2, 2, 2, 2 ;

The hdr_vld values are supposed to be indexes into the hdr_vld_table array.  But as you can see, the first hdr_vld index value of 0 is valid... but all the rest (2) extend past the end of the hdr_vld_table array.  In Perry case, instead of 2 he sees a value of 40.  I suspect this is just uninitialized values which never get set.

This needs to be fixed in the met-8.1.1 release.

**Comment by TaraJensen** [comment]
Charge 2780541

**Comment by hsoh-u** [comment]
Created bugfix_1137_pb2nc_hdr_vld branch and modified nc_obs_util.cc.
Merged bugfix branch into develop and master_v8.1 branches.
