### ISSUE TITLE
Enhance Ensemble-Stat, MTD, and Series-Analysis to support the use of python embedding.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1140]

**Comment by TaraJensen** [comment]
Charge 7790971

**Comment by JohnHalleyGotway** [comment]
Recommend the following solution, which applies generally to all tools...
- Use the existing "file_type" config file option and set it to "PYTHON_NUMPY" or "PYTHON_XARRAY".
- Pass the input (forecast and/or observation) files in the typical way, by defining the path to the input file.
- Let the user's python command include the use of a constant string, "MET_PYTHON_INPUT_FILE".
- When processing each input file, replace the MET_PYTHON_INPUT_FILE constant with the  *current* input filename.

With this logic, python embedding should work fine for Ensemble-Stat, Series-Analysis, and MTD.

**Comment by JohnHalleyGotway** [comment]
For example, here's the existing way of running plot_data_plane:

**plot_data_plane PYTHON_NUMPY gefs_rec10.ps \
'name="read_CPC_binary.py gefs-legacy-00z_rfcst-cal_tmean_20170807_8-14day.bin 10";'**

And here is the new variation of logic that I'm adding:

**plot_data_plane gefs-legacy-00z_rfcst-cal_tmean_20170807_8-14day.bin gefs_rec10.ps \
'name="read_CPC_binary.py MET_PYTHON_INPUT_FILE 10"; file_type=PYTHON_NUMPY;'**

**Comment by JohnHalleyGotway** [comment]
Merged code changes into develop and enhanced unit_python.xml with new calls to plot_data_plane, series_analysis, mtd, and ensemble_stat.  Still need to update the docs.

**Comment by JohnHalleyGotway** [comment]
Finished updating config/README and Appendix F of the user's guide with this info.
