### ISSUE TITLE
Fix the MODE Rscripts in met-8.1.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1141]
Marion Mittermaier reports via met-help that the MODE Rscript "mode_quilt_plot.R" is not working in met-8.1.  Please see:
https://rt.rap.ucar.edu/rt/Ticket/Display.html?id=90516

Fix this prior to the met-8.1.1 release.

**Comment by TaraJensen** [comment]
Charge 2702691

**Comment by dwfncar** [comment]
Incorporated changes from Marion and tested fixes on use case from ticket https://rt.rap.ucar.edu/rt/Ticket/Display.html?id=90516.
Committed to develop and master_v8.1 branches.
