### ISSUE TITLE
Enhance Stat-Analysis to read matched pairs via Python Embedding to support evaluation of point forecasts

### ISSUE THREAD

**Issue by TaraJensen** [dtcenter/MET#1143]
Several organizations would like to evaluate point forecasts using MET.  It seems like overkill, but having the same tools computing scores for point forecasts and gridded forecasts simplifies their software support.  It would be good to enhance Stat-Analysis to be able to read in matched pairs via Python embedding and provide a couple of examples of python scripts to fully populate the .mpr data array.

**Comment by TaraJensen** [comment]
Charge 2700001

**Comment by JohnHalleyGotway** [comment]
Committed to the develop branch and updated unit_python.xml to exercise this functionality.
