### ISSUE TITLE
Update AUC equation in MET documentation

### ISSUE THREAD

**Issue by TaraJensen** [dtcenter/MET#1150]
Jeff Hamilton ran across what appears to be an error in our documentation of AUC.  It the user's guide, it's listed as

![image](https://user-images.githubusercontent.com/23195803/59716421-33851f00-91d3-11e9-9edf-010f2414ce8a.png)

Randy has mathmatically confirmed the POFD term should be (POFDsubi+1 - POFDsubi).  It would be good to confirm it is coded that way and then update the LYX documentation.

**Comment by TaraJensen** [comment]
Charge 2780541

**Comment by JohnHalleyGotway** [comment]
FYI, here's the relevant code from contable_nx2.cc.

double Nx2ContingencyTable::roc_auc() const

{

int j;
TTContingencyTable ct;
double area, x_prev, y_prev, x, y;

x_prev = y_prev = 1.0;

for(j=0, area=bad_data_double; j<Nrows; ++j)  {

   // 2x2 Contingency Table for this row
   ct = ctc_by_row(j);

   // Retrieve the ROC point for this row
   x = ct.pofd();
   y = ct.pod_yes();

   if(is_bad_data(x) || is_bad_data(y)) continue;

   // Initialize area to 0 for the first valid point
   if(is_bad_data(area)) area = 0.0;

   // Compute area under the curve using the trapezoid rule
   area += (x_prev - x)*(y_prev + y)*0.5;

   // Save current ROC point as the previous point
   x_prev = x;
   y_prev = y;

}

return ( area );

}

**Comment by rgbullock** [comment]
Assuming the x values are in decreasing order, so that (x_prev - x) is not
negative, this code looks good to me.

Randy

**Comment by JohnHalleyGotway** [comment]
Fixed this in both master_v8.1 and develop.
