### ISSUE TITLE
Practically Perfect Functionality

### ISSUE THREAD

**Issue by lindsayrblank** [dtcenter/MET#1151]
This issue summarizes previous work on and lays out the future work that needs to be done for practically perfect capabilities. 
Related issues: #948 and #1136

Practically perfect is "the forecast that is consistent with that which a forecaster would make given perfect knowledge of the reported events beforehand and the operational constraints associated with the forecasting system." (Hitchens et al. 2013)

**Traditional Steps (from Hitchens et al. 2013)**:
1. Get SPC local storm reports (LSRs).
2. Plot each LSR on an 80x80km grid.
3. Smooth the point data to create a continuous grid using Gaussian smoothing.

**MET Steps**:
1. Interpolate SPC LSRs onto a dx by dy grid using "grid_point_obs" tool (the output of this issue).
2. Smooth the gridded point observations using the Gaussian interpolation method (#948).
3. Output a gridded "practically perfect" field. 

Status Update:
1. Gaussian weighted interpolation is an interpolation method that is now available in all tools that have interpolation as an option in MET 8.1.

**Comment by JohnHalleyGotway** [comment]
The initial functionality was included in met-9.0, but additional testing is required.

**Comment by JohnHalleyGotway** [comment]
Lindsay, please check to see if/what additional work is required for this. If all the work is done, please close this issue.

**Comment by lindsayrblank** [comment]
This functionality was completed through METplus https://github.com/dtcenter/METplus/issues/406.
