### ISSUE TITLE
Run unit tests for master_v8.1 with the Intel -ftrapuv option.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1154]
Development for #1139 revealed a sporadic runtime abort when writing NetCDF output files.  The most recent example was with gen_vx_mask (see below) but when rerun, it completes without error.

This task is to compile the master_v8.1 branch with Intel using the -ftrapuv option and then run the full set of unit tests.  The hope is that this problem will become repeatable and easier to dubug, assuming it has to do with an uninitialized variable somewhere.

/d2/projects/MET/MET_development/MET/met/share/met/../../bin/gen_vx_mask
/d2/projects/MET/MET_development/MET/test_output/gen_vx_mask/DATA_APCP_24_mask.nc
/d2/projects/MET/MET_development/MET/met/share/met/poly/LMV.poly
/d2/projects/MET/MET_development/MET/test_output/gen_vx_mask/POLY_PASS_THRU_APCP_24_LMV_mask.nc
-type poly -value 10 -v 2
DEBUG 1: Input File: /d2/projects/MET/MET_development/MET/test_output/gen_vx_mask/DATA_APCP_24_mask.nc
DEBUG 1: Mask File: /d2/projects/MET/MET_development/MET/met/share/met/poly/LMV.poly
terminate called after throwing an instance of 'netCDF::exceptions::NcEdge'
what(): NetCDF: Start+count exceeds dimension bound
file: ncVar.cpp line:1614
Aborted

**Comment by jprestop** [comment]
The master_v8.1 was compiled with Intel using the -ftrapuv option.  Unit tests were run, excluding the tests for mode graphics and python embedding.  The tests ran successfully until running "regrid_data_plane_GOES_16_AOD_TO_G212", when a segmentation fault was produced.  The log file can be found at dakota:/d2/jpresto/MET/MET_test_output/unit_test.log

/d3/projects/MET/MET_intel_testing/MET-master_v8.1/met/share/met/../../bin/regrid_data_plane \
      /d3/projects/MET/MET_test_data/unit_test/model_data/goes_16/OR_ABI-L2-AODC-M3_G16_s20181341702215_e20181341704588_c20181341711418.nc \
      G212 \
      /d2/jpresto/MET/MET_test_output/regrid/regrid_data_plane_GOES_16_AOD_TO_G212_compute.nc \
      -field 'name="AOD";  level="(*,*)";' \
      -qc 1,2,3 -method MAX \
      -v 1
DEBUG 1: Reading data file: /d3/projects/MET/MET_test_data/unit_test/model_data/goes_16/OR_ABI-L2-AODC-M3_G16_s20181341702215_e20181341704588_c20181341711418.nc
Segmentation fault

ERROR: /d3/projects/MET/MET_intel_testing/MET-master_v8.1/test/perl/unit.pl unit_regrid.xml failed.

**Comment by JohnHalleyGotway** [comment]
John ran this case through the debugger.  And was able to replicate the error Julie got.
However, Howard is right.  This error is due to an uninitialized boolean on line 671 of regrid_data_plane:
   bool has_coord_input;

And that line has already been corrected by another branch of master_v8.1:
   bool has_coord_input = false;

John pulled the tip of the master_v8.1 branch, recompiled with Intel and -ftrapuv, and reran the unit tests:
In dakota:/d3/projects/MET/MET_intel_testing/git/MET/met, run the unit tests:
/d3/projects/MET/MET_intel_testing/git/MET/test/bin/unit_test.sh >& /d3/projects/MET/MET_intel_testing/git/MET/unit_test.log&

**Comment by JohnHalleyGotway** [comment]
All of the unit tests ran without problem using the tip of the master_v8.1 branch with Intel 15.0.2 20150121 and the -ftrapuv option.  Closing this issue.
