### ISSUE TITLE
Enhance MET code to interpret NetCDF COARDS convention as CF compliant file

### ISSUE THREAD

**Issue by jprestop** [dtcenter/MET#1155]
Location to get COARDS convention files:
https://portal.nccs.nasa.gov/datashare/gmao_ops/pub/fp/forecast/Y2019/M06/D24/H00/

**Comment by JohnHalleyGotway** [comment]
Per http://cfconventions.org/, the CF conventions generalize and extend the COARDS conventions.  Therefore, we can interpret COARDS files as being CF-compliant.
Enhanced the logic in the is_netcdf_file.cc source code to check for "CF-", "CF", and "COARDS".  Tested using the data mentioned above.  Committed change to the master_v8.1 branch directly and the develop branch.

**Comment by JohnHalleyGotway** [comment]
Fixed in develop and master_v8.1.
