### ISSUE TITLE
The computed CAPE value is not correct

### ISSUE THREAD

**Issue by hsoh-u** [dtcenter/MET#1167]
There was typo in the variable name for computed cape value: cape_val VS. cape_val4. Deleted cape_val4.

**Comment by JohnHalleyGotway** [comment]
John will install a development version of the MET master_v8.1 branch on Theia and ask Perry to test the derivation of CAPE there.  Tara and Jonathan are the NCAR scientists working on this and Howard is the engineer fixing it.

**Comment by JohnHalleyGotway** [comment]
The GitHub/NCAR/MET master_v8.1 branch is compiled on theia here:
   /scratch4/BMC/dtc/MET/MET_development/MET-master_v8.1/met/bin

Run commands like this:
   **module use /contrib/modulefiles
   module load intel anaconda/anaconda2-4.4.0 met/8.1
   /scratch4/BMC/dtc/MET/MET_development/MET-master_v8.1/met/bin/pb2nc**

**Comment by JohnHalleyGotway** [comment]
Howard merged the bugfix branch into develop.  And Julie compiled a tarball built from the develop branch on WCOSS (tide) for Perry to test:

**module use /global/noscrub/Julie.Prestopnik/modulefiles
module load met/8.1_dev**

**Comment by JohnHalleyGotway** [comment]
Perry corrected the CAPE output in the VSDB log files and we should do a new comparison of CAPE values between VSDB and PB2NC to see if they are closer.

VSDB CAPE values from log file:
   /stmpp2/Perry.Shafran/tmpnwprd/verf_gridtobs_nam_00/00/gto.nam00.out
MET CAPE values from PB2NC:
   /meso/noscrub/Perry.Shafran/metplus_test/nam/conus_sfc/prepbufr.nam.2019091000.nc

Also need to compare the PBL values to see how they match up.

**Comment by JohnHalleyGotway** [comment]
On 9/20/2019 Perry confirmed that the CAPE values computed by PB2NC match the VSDB values very well.

There are 2 main source of difference:

(1) VSDB uses all input vertical levels in the CAPE computation, while MET only uses the levels which meet the specified quality marker threshold.  This leads to a difference, but setting the PB2NC quality marker threshold to the maximum value of 15 eliminates it.  And having the ability in MET to filter by quality marker is preferable anyway.

(2) VSDB computes CAPE rounded to the nearest integer, while MET computes CAPE with a decimal component.  And the higher precision in MET is preferable anyway.
