### ISSUE TITLE
Change the behavior of -qc option for regrid_data_plane

### ISSUE THREAD

**Issue by hsoh-u** [dtcenter/MET#1168]
This is a request from Ho-Chun Huang (https://rt.rap.ucar.edu/rt/Ticket/Display.html?id=91097).

Current implemantation:

"-qc 0" is to use ADO with quality flag=0 ONLY
"-qc 1" is to use ADO with quality flag=1 ONLY
"-qc 2" is to use ADO with quality flag=2 ONLY
"-qc 1,2" is to use ADO with quality flag=1 or 2 ONLY

If it is the case, then I think it might have to be changed to

-qc 0, is to use ADO with quality flag<=0, i.e., quality flag=0.
-qc 1, is to use ADO with quality flag<=1, i.e., quality flag=0 and quality
flag=1.
-qc 2, is to use ADO with quality flag<=2, i.e., quality flag=0, 1, and 2
(All AOD)

**Comment by Ho-ChunHuang-NOAA** [comment]
Using current functionality of regrid_data_plane, I confirmed that

AOD quality flag<=0 is equivalent to "-qc 0"
AOD quality flag<=1 is equivalent to "-qc 0,1"
AOD quality flag<=2 is equivalent to "-qc 0,1,2"

Therefore, maybe there is no need to change the behavior of -qc option for regrid_data_plane.  It would be helpful if the description of using -qc can be expanded (to include the way to perform qc**<=**#) in User's Guide.

**Comment by hsoh-u** [comment]
The requester agreed that comma separated quality value list with -qc option meets his requirement.
   -qc 0,1 is for QC value equal or less than 1
   -qc 0,1,2 is for QC value equal or less than 2
