### ISSUE TITLE
MET configure/build error with rpl_malloc in config.h

### ISSUE THREAD

**Issue by dwfncar** [dtcenter/MET#1171]
In config.h, the lines are causing build issues

#define malloc rpl_malloc
#define realloc rpl_realloc

Commenting these out allows build to proceed.
Is this an issue in the autoconf files?

Problem reported in RT ticket 91161

https://rt.rap.ucar.edu/rt/Ticket/Display.html?id=91161

**Comment by fillmoredavid** [comment]
On Ubuntu, problem is fixed in configure.ac, comment out AC_FUNC_MALLOC and AC_FUNC_REALLOC.
Dakota configure still OK, need to test on other systems ...

**Comment by dwfncar** [comment]
On Ubuntu comment out AC_FUNC_MALLOC and AC_FUNC_REALLOC lines in configure.ac.
Dakota build still OK.  Need to test on other systems ...

**Comment by dwfncar** [comment]
configure.ac change committed to master v8.1 branch.  Need to test on other systems other than ubuntu and dakota.
