### ISSUE TITLE
RMW-Analysis: new tool to analyze output of TC-RMW

### ISSUE THREAD

**Issue by dwfncar** [dtcenter/MET#1178]
Create new rmw_analysis tool to read select output files of tc_rmw,
create config file specified aggregate statistics, write to a summary netcdf file.

**Comment by dwfncar** [comment]
We need a new tool read the output of tc-rmw and average results across multiple cases. Consider also including the standard deviation or variance. Could also consider min/max and percentiles.

**Comment by JohnHalleyGotway** [comment]
Kathryn will send John the location of the HWRF model output and the ATCF tracks themselves, and John will pull many cases from theia for David's testing.

**Comment by dwfncar** [comment]
Merged to develop for MET9_beta4.
