### ISSUE TITLE
Create an option for installing MET executables into "exec" rather than the default "bin" directory.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1189]
This change is required for met-9.0 to be installed by NCO.  Here's an email from Steven Earle clarifying NCO policy on 08/27/2019:

_There are several different standards out there for structure to install software. You mention autoconf conventions, which is one of the many. NCO standard is "exec" instead of "bin". We can't accept every structure that exists in the world so we enforce and keep it consistent with one of them, namely, "exec". I understand the desire to keep autoconf structure since that's what you're built around, but the choice is either... conform to the operational standard directory structure or continue installing in /usrx where there are no such standards (essentially, forgetting this conversation ever happened and stick with status quo)._

For this task, investigate the autoconf options for installing into an "exec" subdirectory rather than "bin".  Consider supporting a new makefile directive such as "make install_exec" to copy into "exec" instead of "bin".

**Comment by jprestop** [comment]
This is much simpler than anticipated and this functionality already exists.  The user simply needs to override the default bin directory using --bindir.  See example below:
./configure --prefix=${MET_DIR} **--bindir=/d1/jpresto/MET/MET_dev/9.0_beta/exec** --enable-grib2 --enable-modis --enable-mode_graphics --enable-lidar2nc --enable-python
