### ISSUE TITLE
The PBL value derived by PB2NC does not match VSDB.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1199]
We need to update PB2NC to make sense of the discrepancies in PBL values computed in VSDB and MET.

Perry is generating test output on WCOSS.

Input PrepBUFR file:
/gpfs/dell1/nco/ops/com/nam/prod/nam.20190919/nam.t06z.prepbufr.tm06

And when the run is complete, you'll be able to find files in this directory:
/stmpp1/Perry.Shafran/tmpnwpara/verf_gridtobs_nam_00/00

The prepfit.out.nam file will contain the profile, with station ID, of the Z, T, U, V, and P that goes into the calculation of the PBL height.  Search for "staid".
The gto.nam.00 file will contain the PBL values for each station.  Search for "PBL".

**Comment by JohnHalleyGotway** [comment]
John pulled down the sample files from WCOSS to dakota:

[johnhg@dakota]% ls /d3/projects/MET/MET_Help/shafran_data_20190920
gto.nam00.out  nam.t06z.prepbufr.tm06.nr  prepfit.out.nam

**Comment by JohnHalleyGotway** [comment]
PB2NC should derive PBL observations only for ADPUPA and AIRCFT message types.

From John on 9/27/2019:
First question: should PBL be derived only from a particular message type (likely ADPUPA)?
The log you sent me has 86 unique PBL observations, while PB2NC wrote 142,521 of them, of which, 38,549 are unique.

From Perry on 9/27/2019:
Yes, this logic should only apply to ADPUPA message types.
However, we also would like to apply this logic to aircraft profiles as well, but they are *not* found in the prepbufr file that you have right now.  There is another bufr file that contains these.  Do you think that whatever logic you come up with can be applied to other data types if necessary?

**Comment by JohnHalleyGotway** [comment]
Howard, I picked a single ADPUPA observation to test more: 70398, where MET's PBL = 84.607 while VSDB's PBL = 140.

Then I reconfigured PB2NC to only process ADPUPA... and only process that station:
message_type = [ "ADPUPA" ];
station_id = [ "70398" ];

But that run yielded 2 PBL values (-10034 and 174.05) for that station!?
  ADPUPA 70398 20190919_000000 55.05 -131.59 35 PBL NA     0.0000 52 -10034.000000  
  ADPUPA 70398 20190919_000000 55.05 -131.59 35 PBL NA     0.0000 2    174.050000 

Perhaps you could start by debugging that discrepancy?  Why processing all the stations vs a single station yields a different result.  They should definitely be the same!

FYI, this test data is all on dakota in /d3/projects/MET/MET_Help/shafran_data_20190920.

**Comment by JohnHalleyGotway** [comment]
Reassigned this from met-8.1.2 to met-9.0 since it was taking too long to be included in a bugfix release.

**Comment by hsoh-u** [comment]
The PBL is computed only for ADPUPA.
- The max vertical level was increased to 256 (was 100)
- Changed the linear interpolation to logarithm interpolation.
