### ISSUE TITLE
Add support for Gaussian interpolation option for interpolating to point locations.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1223]
Add support for Gaussian interpolation option for interpolating to point locations.

Enhance compute_horz_interp() function in interp_util.cc to support GAUSSIAN option.  Also, consolidate many function arguments into a class or struct and include in it a DataPlane which stores the computed Gaussian weights.  This ensures we only compute the weights once instead of separately for each call to compute_horz_interp().

Also updated data/config/README with the changes to the details.

Also add new config option for "gaussian_trunc" for the truncation factor, currently hard-coded to 3.5.

**Comment by hsoh-u** [comment]
Merged bug_1223_gaussian branch to develop
