### ISSUE TITLE
Break out Gaussian algorithm into GAUSSIAN and MAXGAUSS.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1234]
Gaussian is supported in 3 contexts:
(1) When interpolating gridded model data to point locations.  This is the "interp" dictionary for Point-Stat.  This logic is clear.
(2) When smoothing gridded model data using the "interp" dictionary in Grid-Stat.
(3) When regridding model data using the "regrid" dictionary across many MET tools.

These are the configurable options to consider:
   - method = GAUSSIAN
   - width = N
   - shape = SQUARE or CIRCLE
   - gaussian_dx = N
   - gaussian_radius = N

The logic for cases (2) and (3) is a little bit confusing.  We first compute the MAXIMUM value over the neighborhood as defined by shape and width.  And we second apply the Gaussian smoother as defined by gaussian_dx and gaussian_radius.

It's confusing to me that the logic for (1) differs from (2) and (3), even when all are named GAUSSIAN.  Technically, you can skip the application of the maximum value by setting:
   method = GAUSSIAN;
   width = 1;

This computes the maximum over a single point and then applies the Gaussian smoother.  

Here's another option to consider...

Let method = GAUSSIAN be supported in all 3 cases above... but do NOT include computation of a maximum value there.

Define a new method = MAXGAUSS, but support it in only cases (2) and (3), not (1).

This really comes down to a question of usability and documentation.  Longterm, is it worth documenting/supporting/teaching GAUSSIAN and MAXGAUSS, where width really only applies to MAXGAUSS.  Or is it better to leave it as-is and document these details.

**Comment by ahijevyc** [comment]
Without knowing about SPC's extensive use of NCEP grid 211, it is a little perplexing why the default gaussian_dx is 81.271 km. I think it should be documented in the configuration README that this default value specifically pertains to NCEP storage grid 211, Regional - CONUS (Lambert Conformal), which has a nominal grid spacing of 80km. It is not generally appropriate for an arbitrary grid. 

Even better, can the gaussian_dx parameter be dropped? Can we just get it from the output grid "to_grid" definition?

Thanks for your consideration!
