### ISSUE TITLE
Fix bug in processing CF Compliant NetCDF valid time stamp.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1238]
This is a bug that Tina Kalb found when running MODE on NetCDF CESM data.  A sample input file can be found in /scratch/Tina/MetPlus.globe.2014-06-01-00000.cam.h1.2014-06-02-00000.nc.

Run this command through the debugger to see the problem:
   plot_data_plane MetPlus.globe.2014-06-01-00000.cam.h1.2014-06-02-00000.nc plot.ps 'name="PRECC"; level="(0,*,*)";' -v 5

The valid time is being reported as "valid time: 20141102_000000".  However, it should actually be "32 days since 2014-05-01 00:00:00" = "2014-06-02 00:00:00".

Look on line 318 of nccf_file.cc:
 318       ValidTime.add(add_to_unixtime(ut, sec_per_unit, time_value, no_leap_year));

Step into "add_to_unixtime()" on line 71 of is_leap_year.cc:
 71 unixtime add_to_unixtime(unixtime base_unixtime,

The logic in this function is not correct.  Specifically, I don't understand the logic on line 84:
 84     day_offset += day_offset % 365

**Comment by hsoh-u** [comment]
Merged to develop branch
