### ISSUE TITLE
Test ascii2nc python embedding for MONET.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1258]
## Describe the Task ##
Test using python embedding with ascii2nc to ingest observations from MONET.

### Time Estimate ###
Approx 1 week.

### Relevant Deadlines ###
To be completed for met-9.1.  No specific deadline.

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required (John HG)
- [X] Select **scientist(s)** or **no scientist** required (Barry Baker and Tara Jensen)

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones
- [X] Select **milestone**

**Comment by bbakernoaa** [comment]
- Create a WCOSS environment using Intel Python
- install MONET or MONETIO (conda install -c bbakernoaa monet)
- Use custom ingest 
     * write python script to ingest AIRNOW from MONET for use in custom ingest
     * set MET_PYTHON_EXE in custom ingest to the MONET environment
     * compute statistics with PM2.5 and compare to standard METplus tools 

for example of monet:

```python
import monet as m
import pandas as pd
dates = pd.date_range(start='2019-01-01',end='2019-01-02',freq='H')
df =m.obs.airnow.add_data(dates)
```

**Comment by bbakernoaa** [comment]
@JohnHalleyGotway I worked on separating the code for MONET so that the I/O was in its own repository. This allows us to have less dependencies so that it will be easier to get through any type of operation problems

The new repository is monetio, https://github.com/noaa-oar-arl/monetio.  It is used the same way as monet but doesn't include additional functionality.  This is left to monet itself for the XarrayAccessor which includes a lot of functions like regridding, horizontal, vertical, and temporal along with a new PandasAccessor which adds capabilities for point data.

**Comment by bbakernoaa** [comment]
Can someone send me an example file of the ascii2nc output?

**Comment by hsoh-u** [comment]
github does not accept "nc" extension. I renamed it to "*.txt". Please renamed the attached files:
- AERONET_NA_2015.lev20_test.txt to AERONET_NA_2015.lev20_test (input)
- AERONET_NA_2015.lev20_test.nc.txt to AERONET_NA_2015.lev20_test.nc (output)

[AERONET_NA_2015.lev20_test.txt](https://github.com/NCAR/MET/files/4345424/AERONET_NA_2015.lev20_test.txt)

[AERONET_NA_2015.lev20_test.nc.txt](https://github.com/NCAR/MET/files/4345416/AERONET_NA_2015.lev20_test.nc.txt)

**Comment by bbakernoaa** [comment]
Thanks @hsoh-u I'll take a look and see what I can do.  I'm hoping to just write a function to output into the NetCDF file directly from MONET. This would solve a lot of problems for integrating MONET with MET.  I'll give it a shot tomorrow!

**Comment by bbakernoaa** [comment]
Is there some documentation on this NetCDF file? I think I understand most of it but I want to see if we can put multiple stations in a single file and how that is done.

**Comment by JohnHalleyGotway** [comment]
Hi Barry,

There are several point-preprocessing tools in MET (ascii2nc, pb2nc,
lidar2nc, and madis2nc) which all write to a common NetCDF point
observation format.

This file format is described in section 4.1.3 of the MET User's Guide:
https://dtcenter.org/sites/default/files/community-code/met/docs/user-guide/MET_Users_Guide_v9.0.pdf
Starting on page 147.

Please let me know if you find anything incorrect in the details listed
there, and we'll correct it.  It's always tough to keep the docs totally up
to date.

But there's something I think you might find helpful.  The ascii2nc tool
can read a simple 11-column ascii file format and reformat into this NC
file format.  For example, you can use sample data that's included with MET:

https://github.com/NCAR/MET/blob/master_v9.0/met/data/sample_obs/ascii/sample_ascii_obs.txt

And then run it like this:
*ascii2nc sample_ascii_obs.txt sample_ascii_obs.nc
<http://sample_ascii_obs.nc>*

So that reformats ascii to nc.  And we do also have an Rscript that we use
for testing that goes the other way:
https://github.com/NCAR/MET/blob/master_v9.0/met/scripts/Rscripts/pntnc2ascii.R

And then run it like this:
*Rscript pnt2ncascii.R sample_ascii_obs.nc <http://sample_ascii_obs.nc> >
obs.txt*

To answer your specific question, yes, you can have different station id's
in the same file.  The list of unique station id strings are defined in the
hdr_sid_table variable.  That stores the unique station id's and hdr_sid is
an integer index into that array.

You may find it easier to write to that 11-column ascii file format and
then run ascii2nc to do the reformatting.  Or in met-9.0, we added python
embedding for ascii2nc.  So you could run a python script to serve up data
in that 11-column format into ascii2nc via memory.  That'd save the writing
of one intermediate file.

Thanks,
John

**Comment by bbakernoaa** [comment]
@JohnHalleyGotway I'm a little confused by the first column Message_Type.  Is there a generic one for surface observations.

**Comment by JohnHalleyGotway** [comment]
Please look in table 4.4 of the MET User's Guide on page 149:
https://dtcenter.org/sites/default/files/community-code/met/docs/user-guide/MET_Users_Guide_v9.0.pdf

John

**Comment by bbakernoaa** [comment]
Could you please elaborate on some of these.  For instance there are multiple values listed on page 143 for message type but in reality it is not described what they are or if they are used in different ways for the statics.  

Column 10 is the QC but I cannot find anywhere what the QC values are.  Different observations have different definitions and am not sure if I need to set these to a standard QC value or what.  

If passing in memory how you would like this to be formatted?  pandas data frame? numpy array? dict? It isn't clear here how to do that.

**Comment by bbakernoaa** [comment]
Also elevation and height are in there twice, Maybe you are setting them so one could be agl and the other msl?

**Comment by bbakernoaa** [comment]
If I write this out to a file is there a specific format that is required (tab delimited, whitespace, csv, etc....)?

**Comment by bbakernoaa** [comment]
btw I think that I have a generic enough function to generate a pandas data frame interpretation of the little_r formatted file.  I'm going to test it out this week on WCOSS and see.

**Comment by JohnHalleyGotway** [comment]
Formatted the issue description using the newly adopted issue templates.
@bbakernoaa please find responses below:

1. Message types:
Point observations are read by the Point-Stat and Ensemble-Stat tools.  Those tools compute stats separately for each observation message type you request.  For example, you could get stats for upper-air temperature (i.e. message_type = ADPUPA) versus surface temperature (i.e. message_type = ADPFSC).  Defining the message_type is a way of grouping similar observations together.  The examples I gave were using the PREPBUFR naming conventions, but MET enforces no such conventions.  You can use any string (no embedded whitespace!) you'd like and then request observations of those type in the Point-Stat and Ensemble-Stat config files...
   message_type   = [ "ADPUPA", "ADPSFC" ];
Not sure on the best documentation for PrepBUFR, but this link lists a description of the message types they use:
https://rda.ucar.edu/datasets/ds337.0/docs/README_readpb

2. QC values
The QC value is really a string.  In PrepBUFR, quality control is stored as an integer (lower means better), but in MADIS they're stored as strings.  So in MET, we stored them as strings.  MET does NOT do apply and QC logic, other than to exclude observations based on the incoming QC values.
From the Point-Stat config file:
   obs_quality    = [ "0", "1", "2", "3" ];
If the "obs_quality" is empty, use all obs regardless of their QC string.  If not empty, only use obs whose QC string appears in the list.  If you have no QC information for your observations, just put "NA" in that column.

3. Pandas formatting
This is the best example I have to illustrate how ascii2nc expects the python data to be formatted:
https://github.com/NCAR/MET/blob/master_v9.0/met/scripts/python/read_ascii_point.py
        # Read and format the input 11-column observations:
        #   (1)  string:  Message_Type
        #   (2)  string:  Station_ID
        #   (3)  string:  Valid_Time(YYYYMMDD_HHMMSS)
        #   (4)  numeric: Lat(Deg North)
        #   (5)  numeric: Lon(Deg East)
        #   (6)  numeric: Elevation(msl)
        #   (7)  string:  Var_Name(or GRIB_Code)
        #   (8)  numeric: Level
        #   (9)  numeric: Height(msl or agl)
        #   (10) string:  QC_String
        #   (11) numeric: Observation_Value

        point_data = pd.read_csv(input_file, header=None, delim_whitespace=True, keep_default_na=False,
                          names=['typ', 'sid', 'vld', 'lat', 'lon', 'elv', 'var', 'lvl', 'hgt', 'qc', 'obs'],
                          dtype={'typ':'str', 'sid':'str', 'vld':'str', 'var':'str', 'qc':'str'}).values.tolist()

4. Elevation vs height
The elevation in column 6 is the elevation of the station.  The height in column 9 is the height of the observation.  For example, for soundings, the station elevation remains constant while the height increases as the ballon ascends through the atmosphere.  For surface observations, the elevation = height.
MSL vs AGL is a great question!  And MET does not really enforce any conventions here.  Currently, it's the user's responsibility to ensure that the vertical coordinate of the point observation (MSL or AGL) is consistent with the vertical coordinate of the model output (MSL or AGL).  MET doesn't care which is used, but they need to be consistent for vertical interpolation to work well.  Seems like we could do better in this regard!

5. File format
All of the MET's ASCII input and output is whitespace delimited.

**Comment by bbakernoaa** [comment]
@JohnHalleyGotway could you point me to the example METPlus script.  I seem to have lost where that was in the data directory.

**Comment by bikegeek** [comment]
@bbakernoaa, are you looking for the METplus config file for the ASCII2NC wrapper?  If so, it is found in the $METPLUS/parm/use_cases/met_tool_wrapper/ASCII2NC.  I hope that is what you were looking for.

**Comment by bbakernoaa** [comment]
I'm looking for an example of using ascii2nc in metplus to compare to a datasets (say FV3) for example

**Comment by bikegeek** [comment]
@bbakernoaa, the ASCII2NC wrapper is new in the METplus 3.0 release and I verified with a scientist who went through all the use cases- there isn't an example use case that matches what you are looking for.

**Comment by TaraJensen** [comment]
@bbakernoaa,   the process flow to use Python Embedding for point verification is more of a METplus thing including calls to ASCII2NC and Point-Stat.  

aeronet data -> python embedding <-> ascii2nc -> netcdf output and GFS data (aka FV3) -> point-stat

This particular GitHub issue is focused solely on the first part:
aeronet data -> python script used for embedding <-> ascii2nc -> netcdf output

Python embedding for ascii2nc solely supports Pandas.  An example of how to do this from your own user environment is now documented as a METplus use-case:   
[ASCII2NC with Python embedding using your environment](https://ncar.github.io/METplus/Users_Guide/met_tool_wrapper/ASCII2NC/ASCII2NC_python_embedding_user_py.html#sphx-glr-users-guide-met-tool-wrapper-ascii2nc-ascii2nc-python-embedding-user-py-py)
with path to it is: $METplus/Users_Guide/met_tool_wrapper/ASCII2NC/ASCII2NC_python_embedding_user
@georgemccabe is the best person to assist with supporting the use-case. NOTE: We should probably bring the request for help back into met-help@ucar.edu, rather than cluttering up this issue.

Once you get the ASCII2NC portion working, we can move forward with getting the output into Point-Stat to evaluate GFS or another model/simulation.  Make sense?

**Comment by JohnHalleyGotway** [comment]
I am closing the GitHub issue for MET because it is not clear what code changes are required to support this work. If additional needed functionality is identified, recommend that we create a new GitHub issue to define the feature request.
