### ISSUE TITLE
ascii2nc does not compile if python is disabled

### ISSUE THREAD

**Issue by honnorat** [dtcenter/MET#1267]
I was not able to compile latest `develop` branch (from commit 22b1ee4ba, precisely) without `--enable-python` passed to `configure`.

The culprit is here: https://github.com/NCAR/MET/commit/20fcf4f31bffb5b9393f93de7bf00af7785d9122#r37494338

Python code without correct `#ifdef` directives.

**Comment by JohnHalleyGotway** [comment]
Thanks for letting us know.  This issue is fixed by:
https://github.com/NCAR/MET/commit/c329807047e165e405d3a6f8d7294ea0eb2dd76d
