### ISSUE TITLE
banding in Grid Diag 2d pdf of precip vs column water vapor

### ISSUE THREAD

**Issue by dwfncar** [dtcenter/MET#1279]
## Describe the New Feature ##
There is banding in Grid Diag 2d pdf of precip vs column water vapor

The precip variable appears to be clustering around certain values.

Interchanging precip and CWV in config dictionary reverses variable order
as expected but does change pdf distribution.

It would be good to more fully test this tools using additional fields (850 temp, 500mb hgt, 250mb wind)

It would also be good to test on a different dataset to determine if it's the current test precip that's the problem.

### Acceptance Testing ###
*List input data types and sources.*
*Describe tests required for new functionality.*

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*
*Larger issues should be broken down into sub-issues.*

### Relevant Deadlines ###
Should be done by sometime in May

### Funding Source ###
7790971

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones
- [x] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to other METplus components.
Delete items that do not apply.
- [ ] Define new issue for METplus.
- [ ] Define new issue for METdb.
- [ ] Define new issue for METviewer.
- [ ] Define new issue for METexpress.
- [ ] Define new issue for METcalcpy.
- [ ] Define new issue for METplotpy.

banding in Grid Diag 2d pdf of precip vs column water vapor

precip variable appears to be clustering around certain values.
Interchanging precip and CWV in config dictionary reverses variable order
as expected but does change pdf distribution.

**Comment by michelleharrold** [comment]
Tested 24-h accumulated precip and PWAT (at day 5/120 h fcst). In testing, the suggested ranges and bins were modified, which yielded more appropriate results. The output from the grid-diag tool was plotted to ensure the banding issue was resolved. Testing revealed no problems in the code, but updates were made to (1) apply the mask before computing data min/max values and (2) keeping track of those min/max values over the entire series.
