### ISSUE TITLE
Suspected memory corruption bug in PB2NC on WCOSS.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1286]
## Describe the Problem ##
Perry Shafran at NOAA/EMC found odd behavior using METplus-3.0/met-9.0 on the WCOSS machine venus.  PB2NC creates ASCII output files for each message type (e.g. *_ADPUPA.txt) even though the "-dump" command line option has not been used.  John HG tested and confirmed this behavior on venus, but the problem does not appear on NCAR machines.  I also confirmed that recompiling with code changes either makes the behavior the same... or disappear, depending on the location of the change.  I strongly suspect this is a memory corruption bug where some other code is stomping on the memory of the boolean "dump_flag" variable.

RT Ticket:
https://rt.rap.ucar.edu/rt/Ticket/Display.html?id=94683

### Expected Behavior ###
Those ASCII output files should only be written when the "-dump" command line option is used.

### Environment ###
Describe your runtime environment:
1. Machine: WCOSS Venus.
2. Version: met-9.0

### To Reproduce ###
Describe the steps to reproduce the behavior:
1. Log on to venus.
2. Navigate to /u/John.H.Gotway/MET/MET_Help/shafran_data_20200323.
3. Run the script test_pb2nc.sh
4. Check for the ASCII output files being written and the following log message being printed:
      DEBUG 1: Dumping to ASCII output directory:     .

### Relevant Deadlines ###
4/1/2020 prior to the WCOSS production switch while Venus is still available.

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [X] Select **engineer(s)** or **no engineer** required (John HG)
- [X] Select **scientist(s)** or **no scientist** required (Perry Shafran)

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)**

### Projects and Milestone ###
- [X] Review **projects** and select relevant **Repository** and **Organization** ones
- [X] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [X] NONE [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above.
- [x] Fork this repository or create a branch of **master_\<Version>**.
Branch name: `bugfix_<Issue Number>_master_<Version>_<Description>`
- [x] Fix the bug and test your changes.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**, listing the **\<Issue Number\>** in the title.
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Complete the steps above to fix the bug on the **develop** branch.
Branch name: `bugfix_<Issue Number>_develop_<Description>`
TO BE DONE BY HOWARD SOH.
- [x] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Testing to see if @jprestop receives this notification

**Comment by JohnHalleyGotway** [comment]
Testing on Venus in:
/u/John.H.Gotway/MET/MET_Help/shafran_data_20200323/pb2nc

This same behavior also exists with met-8.1.  So this is likely an old bug, not newly introduced in met-9.0.  It does not exist for met-8.0, for which D_PBL and D_CAPE cannot be derived.

Julie, likely no need to recompile met-9.0 with -ftrapuv if it wasn't introduced by met-9.0.

**Comment by PerryShafran-NOAA** [comment]
I did not see these files introduced in older versions of MET.  The first time I noticed it was the beta4 version of METv9.  Is it possible that they were produced but then deleted by the code?  I ran plenty interactive METplus runs with the older 8.1 version but never saw the code.

I also want to add that I have not updated to METplus v3.  I am working on the beta1 version of METplus v3 from last fall.  Could that be a source of error?

Thanks!

Perry

**Comment by JohnHalleyGotway** [comment]
@PerryShafran-NOAA, I'm not all that surprised you didn't see this behavior in early versions.  Memory corruption is difficult to track down and dependent on the exact configuration you're running.  I count us lucky to have a pattern that's so repeatable.

More testing with: /u/John.H.Gotway/MET/MET_Help/shafran_data_20200323/pb2nc/run_pb2nc_8.1.sh

Trying to narrow down the behavior.  The problem persists with:
   export OBS_BUFR_VAR_LIST="[\"XXX\",\"D_CAPE\"]";
Where XXX is TOB, QOB, UOB, or VOB, but PMO, TDO, PWO, TOCC, D_RH, HOVI, CEILING, or D_PBL.  Also, order doesn't matter... XXX, D_CAPE and D_CAPE, XXX produce the error.

**Comment by JohnHalleyGotway** [comment]
Good news, I found the offending lines and it's very easy to fix:
https://github.com/NCAR/MET/blob/master_v9.0/met/src/tools/other/pb2nc/pb2nc.cc

Starting on line 147.  There are now 8 variables to derive.   So I'll change the 6 to an 8 and add the codes for CAPE and PBL.

```
// Number of variable types which may be derived
static const int n_derive_gc = 6;
```

```
// Listing of grib codes for variable types which may be derived
static const int derive_gc[n_derive_gc] = {
    dpt_grib_code,  wdir_grib_code,
   wind_grib_code, rh_grib_code,
   mixr_grib_code, prmsl_grib_code
};
```

The array overflow occurred on line 2365:
```
bufr_derive_code[vIdx] = bufr_var_index;
```

**Comment by JohnHalleyGotway** [comment]
Adding @hsoh-u as an assignee so he can fix this bug in the develop branch.

**Comment by JohnHalleyGotway** [comment]
Still need to delete the development branch for this issue:
bugfix_1298_master_v9.0_point2grid
