### ISSUE TITLE
Enabled gaussian filtering on GOES16/17 data (point2grid)

### ISSUE THREAD

**Issue by hsoh-u** [dtcenter/MET#1291]
### Describe the Task ###
The Gaussian filtering at point2grid was not enabled GOES16/17 data. The test case (METplus) will need the Gaussian filtering for GOES16/17 data.

### Time Estimate ###
1 project day

### Funding Source ###
2760811 for GOES16

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: Howard Soh
- [x] Select **scientist(s)** or **no scientist** required: Lindsay Blank

### Labels ###
- [X] Select **component(s)**
- [X] Select **priority**
- [X] Select **requestor(s)** NA

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones
- [x] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above.
- [x] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [x] Complete the development and test your changes.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **develop**, listing the **\<Issue Number\>** in the title.
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Close this issue.

**Comment by hsoh-u** [comment]
Additional modifications to change double type "prob_cat_thresh" to SingleThresh type.:
- met/doc/MET_Users_Guide/Reformat_Point/MET_Users_Guide_Reformat_Point.lyx
- met/src/tools/other/point2grid/point2grid.cc
- test/xml/unit_point2grid.xml

**Comment by JohnHalleyGotway** [comment]
As discussed via Slack, update the NetCDF output variable names to include the threshold used to define the probabilities.
