### ISSUE TITLE
The seg fault with point2grid

### ISSUE THREAD

**Issue by hsoh-u** [dtcenter/MET#1298]
## Describe the Problem ##
Hank found there was a segmentation fault on running point2grid on eyewall. The input file contains 
385734 observations, 116127 headers, and additional 116127 headers (instrument types and report types). The segmentation fault happens between following two lines:
   int obs_qty_ids[nobs];
   IntArray var_index_array;

### Expected Behavior ###
No segmentation fault

### Environment ###
It happens at dakota

### To Reproduce ###
./point2grid prepbufr.gdas.2017060300.nc G212 out.nc -field 'name="TMP"; level="Z2";'

### Relevant Deadlines ###
4/22 for met 9.1 beta1

### Funding Source ###
164951  NOAA JTTI FV3 SAR

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones
- [x] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **master_\<Version>**.
Branch name: `bugfix_<Issue Number>_master_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **master_\<Version>**, listing the **\<Issue Number\>** in the title.
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name: `bugfix_<Issue Number>_develop_<Description>`
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Still need to delete the development branches for this issue:
bug_1298_point2grid_segfault
bugfix_1298_master_v9.0_point2grid
