### ISSUE TITLE
Incorporate recent changes from the transition Google doc and merge into develop

### ISSUE THREAD

**Issue by jprestop** [dtcenter/MET#1321]
This is a sub-issue of #1217 .

## Describe the Sub-Issue ##
Incorporate recent changes from the transition Google doc MET Documentation Updates During Transition from Lyx to Sphinx: [https://docs.google.com/document/d/1nCPBzu0eYognWWDHyocF3riuzydkF01N87cDWG3Bu0g/edit](url)
and merge into devleop

### Time Estimate ###
1 day

### Assignee ###
- [x] Select **engineer(s)** John HG and Howard
- [x] Select **scientist(s)** or Dan

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones
- [x] Select **milestone**

**Comment by lisagoodrich** [comment]
I have updated the MET Documentation Updates During Transition from Lyx to Sphinx (line above).  There are still 6 outstanding issues I wasn't able to finish.  On that sheet I bolded my roadblocks at the bottom of each open item.  John HG, Dan and Howard please review and let me know if I can help.  Or feel free to modify branch "task_1217_lyx_to_sphinx" and let me know you'll be working on the file so I'm not working on it at the same time.

**Comment by JohnHalleyGotway** [comment]
John HG finished reviewing the notes in:
https://docs.google.com/document/d/1nCPBzu0eYognWWDHyocF3riuzydkF01N87cDWG3Bu0g/edit

- Committed one change to reformat_point.rst on the task_1217_lyx_to_sphinx branch.
- Confirmed that all doc changes from bugfix_1294_master_v9.0_ens_spread are present on the develop branch.  The ensemble-stat.rst and appendixC.rst files are fine.

**Comment by lisagoodrich** [comment]
I pulled in the changes from the develop branch.  BUT your comments about the "TEMP_prob_ge280.0 " are nowhere to be found on the version I used.  I would feel much better if you could look at what I have in the task_1217_lyx_to_sphinx branch.  Please ignore my notes at the top.  (I said where I pulled stuff from.  If it's correct, we can remove it. When I couldn't find the bugfix_1294_master_v9.0_ens_spread I wanted to say what I did use which was the develop branch."

Here are the links for easy review: 

https://github.com/NCAR/MET/blob/task_1217_lyx_to_sphinx/met/docs/Users_Guide/appendixC.rst 
https://github.com/NCAR/MET/blob/task_1217_lyx_to_sphinx/met/docs/Users_Guide/ensemble-stat.rst

**Comment by DanielAdriaansen** [comment]
I'm not sure clarification on the fort.66 format requirement for tc_gen tracker input was added. I will check now.

**Comment by DanielAdriaansen** [comment]
@JohnHalleyGotway where can I view the develop branch version of the user guide?

**Comment by jprestop** [comment]
> @JohnHalleyGotway where can I view the develop branch version of the user guide?

@DanielAdriaansen You can view the most recent update here:
https://ral.ucar.edu/staff/jpresto/work/MET_lisag/Users_Guide/

**Comment by DanielAdriaansen** [comment]
If I would like to make modifications to the RST, is it appropriate to do so now? Or is Lyx still alive?

**Comment by JohnHalleyGotway** [comment]
Lyx is dead. Makes changes to the .rst files in the task_1217 branch.

John

**Comment by jprestop** [comment]
Yes, it is appropriate and suggested to modify the RST file in the task_1217_lyx_to_sphinx branch, as opposed to modifying the documentation in lyx.

**Comment by DanielAdriaansen** [comment]
What's the policy about linking to external documentation? I was going to link to and reference the GFDL cyclone tracker documentation here:
https://dtcenter.org/sites/default/files/community-code/gfdl/standalone_tracker_UG_v3.9a.pdf

Should I just mention the version number and not include a hyperlink? Or maybe use the reference style used throughout the MET user guide and add the GFDL reference to the references section?

**Comment by JohnHalleyGotway** [comment]
Dan,

Not sure. I'd just search for other links in the MET User's Guide (i.e.
search for "http") and make it look somewhat similar.

John

**Comment by lisagoodrich** [comment]
Hi Dan,

The process is really easy.  You just put the link you want in the
documentation.  You don't have to do anything fancy.  If you don't want a
long link to show up, you can do fancier things with just the name showing
up:

`Link text <link URL>`_

I hope this helps.  Please let me know if you need more info.

Lisa
