### ISSUE TITLE
Add references and titles to the MET documentation

### ISSUE THREAD

**Issue by lisagoodrich** [dtcenter/MET#1323]
This is a sub-issue of #1217 .

## Describe the Sub-Issue ##
References and titles need to be added into the documentation or the pages won't show up when the html is built.  An example of this would be found at the top of all documents.  Here is one:

```
.. _point-stat:

Point-Stat Tool
===============
```

### Time Estimate ###
2 days

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones
- [x] Select **milestone**

**Comment by jprestop** [comment]
There is an outstanding item here in the Google doc regarding two references that don't seem to be anywhere else in the latest (9.0.3) PDF User's Guide.  https://docs.google.com/document/d/1fqxbxU23wXWEGTTkp7ZPRw40g93OLn7YdqPjXB5jKLY/edit#
We have asked for Tara's guidance.

**Comment by jprestop** [comment]
Work is complete. Thanks everyone!
