### ISSUE TITLE
add tables to sphinx docs

### ISSUE THREAD

**Issue by lisagoodrich** [dtcenter/MET#1325]
This is a sub-issue of #1217 lyx to sphinx.

## Describe the Sub-Issue ##
None of the tables transferred from lyx to sphinx.  Prioritize this.

### Time Estimate ###
*4 days???  I don't know.*
*Issues should represent approximately 1 to 3 days of work.*

### Assignee ###
- [x] Select **engineer(s)  Lisa Goodrich** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones
- [x] Select **milestone**

**Comment by jprestop** [comment]
This work is complete per conversation with Lisa today.
