### ISSUE TITLE
Show the proper message with madis2nc and ACARS input (not ACARS profiler)

### ISSUE THREAD

**Issue by hsoh-u** [dtcenter/MET#1409]
## Describe the Problem ##
madis2nc supports ACARS profiler and the other ACARS data is not supported (segfault). It's noce to give the proper error message instead of segmentation fault.

### Expected Behavior ###
Show error message instead of seg. fault

### Environment ###
Describe your runtime environment:
1. Machine: Linux Workstation
2. OS: RedHat Linux
3. Software version number(s)

### To Reproduce ###
Describe the steps to reproduce the behavior:
1. madis2nc acars.2020010_1700 test.nc -type acarsProfiles

note: acars.2020010_1700 is not ACARS profiler. The following variables are missing:  profileAirport, profileTime, trackLat, trackLon, altitude, obsTimeOfDay.

### Relevant Deadlines ###
NONE.

### Funding Source ###
NONE.

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required (Howard)
- [x] Select **scientist(s)** or **no scientist** required (None)

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones
- [ ] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **master_\<Version>**.
Branch name:  `bugfix_<Issue Number>_master_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **master_\<Version>**.
Pull request: `bugfix <Issue Number> master_<Version> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Since this is an apparent bug in met-9.1, I'm reassigning this to:
Project = METplus Version 3.1 Support
Milestone = MET 9.1.1 (bugfix)

**Comment by hsoh-u** [comment]
The quality flag variables were excluded from the required variables (reset to NA if the quality flag variables are missing)
