### ISSUE TITLE
The computed gaussian value is not correct

### ISSUE THREAD

**Issue by hsoh-u** [dtcenter/MET#1414]
## Describe the Problem ##
The computed Gaussian value is divided by weight_sum at the end of interp_gaussian() method. This should be removed.

If there is only one valid value at the neighbors which cover the Gaussian matrix, it ended up with the same Gaussian value for neighbors because the multiplied gaussian_weight and the weight_sum are the same.

         gaussian_value += value * gaussian_weight;
         gaussian_value /= weight_sum;

=== simplified code block ===

         count = count_vld = 0;
         gaussian_value = weight_sum = 0.0;
         for(int x_idx=0; x_idx<g_nx; x_idx++) {
            int ix = x - max_r + x_idx;
            for(int y_idx=0; y_idx<g_nx; y_idx++) {
               int iy = y - max_r + y_idx;
               gaussian_weight = g_dp.get(x_idx, y_idx);
               value = dp.get(ix, iy);
               count++;
               if(is_bad_data(value)) continue;
               gaussian_value += value * gaussian_weight;
               weight_sum += gaussian_weight;
               count_vld++;
            }
         }
         
         // Check whether enough valid grid points were found
         if(count_vld > 0) {
            gaussian_value /= weight_sum;
         }

### Expected Behavior ###
The computed Gaussian values for neighbors should be gradually reduced depending on the distance from the center (where the valid data exists)

### Environment ###
Describe your runtime environment:
1. Machine: Linux Workstation
2. OS: RedHat Linux
3. Software version number(s): 9.x

### To Reproduce ###
Describe the steps to reproduce the behavior:
1. Go to dakota
2. ./regrid_data_plane /d3/personal/hsoh/data/RT-95858/1km_TMP_1200UTC_11NOV2016.corrected.nc /d3/personal/hsoh/data/RT-95858/1km_TMP_1200UTC_11NOV2016.corrected.nc gaussian_output.nc -method "MAXGAUSS" -vld_thresh 0
3. Check the value of TMP in gaussian_output.nc

*Post relevant sample data following these instructions:*
*https://dtcenter.org/community-code/model-evaluation-tools-met/met-help-desk#ftp*

### Relevant Deadlines ###
NONE.

### Funding Source ###
NONE.

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required (Howard)
- [x] Select **scientist(s)** or **no scientist** required (Lindsey or John O.)

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones
- [ ] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/NCAR/METplus/issues/new/choose), [MET](https://github.com/NCAR/MET/issues/new/choose), [METdb](https://github.com/NCAR/METdb/issues/new/choose), [METviewer](https://github.com/NCAR/METviewer/issues/new/choose), [METexpress](https://github.com/NCAR/METexpress/issues/new/choose), [METcalcpy](https://github.com/NCAR/METcalcpy/issues/new/choose), [METplotpy](https://github.com/NCAR/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://ncar.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **master_\<Version>**.
Branch name:  `bugfix_<Issue Number>_master_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **master_\<Version>**.
Pull request: `bugfix <Issue Number> master_<Version> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
- [ ] Close this issue.

**Comment by hsoh-u** [comment]
Raname *ps.txt  to *ps

[gaussian_TMP_after.ps.txt](https://github.com/NCAR/MET/files/4928515/gaussian_TMP_after.ps.txt)
[gaussian_TMP_before.ps..txt](https://github.com/NCAR/MET/files/4928516/gaussian_TMP_before.ps.txt)

**Comment by JohnHalleyGotway** [comment]
Closing this issue and WILL NOT FIX. We do still want to divide by the sums of the weights during the Gaussian smoothing step.
