### ISSUE TITLE
Correct spelling errors in documentation

### ISSUE THREAD

**Issue by jprestop** [dtcenter/MET#1456]
This is a sub-issue of #1455 .

## Describe the Sub-Issue ##
We would like to find an automated way to check the spelling in the .rst files.  Lisa may need some help researching tools to do this.  [Doing it through emacs is tedious](https://www.gnu.org/software/emacs/manual/html_node/emacs/Spelling.html).

[PDF/Web Documentation Comparison Chapter Sign Up Sheet - Things for the next version](https://docs.google.com/document/d/1fqxbxU23wXWEGTTkp7ZPRw40g93OLn7YdqPjXB5jKLY/edit?ts=5f1a4de5#)

### Time Estimate ###
1 to 3 days of work

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones
- [x] Select **milestone**

**Comment by lisagoodrich** [comment]
Finished late September 2020.
