### ISSUE TITLE
Improve documentation for Xarray Python embedding

### ISSUE THREAD

**Issue by DanielAdriaansen** [dtcenter/MET#1468]
## Describe the Enhancement ##
More specifics would be helpful on how to use Xarray with Python embedding in MET. Specifically:

1. Currently only DataArray objects are supported
2. The "attrs" associated with the DataArray must conform to MET standards. The documentation should more clearly define the expected types and templates for each supported attribute item, rather than simply a "sample" attributes dictionary.
3. Dataset objects can be used, but include an example of how to subset them and retain the necessary attrs MET requires

### Time Estimate ###
4 hours

### Relevant Deadlines ###
NONE

### Funding Source ###
2790541

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones
- [x] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop** and link the pull request to this issue..
Pull request: `feature <Issue Number> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by DanielAdriaansen** [comment]
Is there a way to check if the object is a DataArray prior to MET trying to access it? I.e., is there C++ code to identify an Xarray DataArray object? Or should this be for the user to enforce?

**Comment by DanielAdriaansen** [comment]
Segmentation fault returned if Dataset object passed. Likely because there are multiple variables in a Dataset and not just a single ndarray.

If a user has a Dataset (ds) object, they can subset it to a single DataArray (da) object _and_ retain the attributes associated with the Dataset like this:
`da = xr.DataArray(ds.varname,attrs=ds.attrs)`

**Comment by DanielAdriaansen** [comment]
See here: https://github.com/dtcenter/MET/issues/1470#issuecomment-680083659 for required attributes and their C++ formats for Python embedding.

**Comment by JohnHalleyGotway** [comment]
@DanielAdriaansen can you please take a look at this issue to see if the work is done? And if so, please close it.
