### ISSUE TITLE
Add supported grids and their definition templates to the documentation

### ISSUE THREAD

**Issue by DanielAdriaansen** [dtcenter/MET#1469]
## Describe the Enhancement ##
Python embedding requires that the user specify a "grid" attribute of the data. This attribute must conform to MET's way for specifying grids, which is currently not readily accessible outside the source code. Add a section containing these grid definition templates to the documentation.

Should it go in the user's guide or contributor's guide?

### Time Estimate ###
4 hours

### Relevant Deadlines ###
NONE

### Funding Source ###
NONE

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones
- [x] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **develop**.
Branch name:  `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop** and link the pull request to this issue..
Pull request: `feature <Issue Number> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by DanielAdriaansen** [comment]
Seems like a lot of this information could be obtained from the *_defs.h files here: https://github.com/dtcenter/MET/tree/master_v9.1/met/src/libcode/vx_grid.

John also suggested running GRIBv2 files through pcp_combine to generate netCDF output, where one could view the CF_compliant grid information which comes from the MET projection code.

**Comment by DanielAdriaansen** [comment]
Actually, after further review it looks like Python embedding has it's own grid support which may or may not be the same as what MET might support. All of the grid definitions Python embedding supports are located in in this file:
https://github.com/dtcenter/MET/blob/master_v9.1/met/src/libcode/vx_data2d_python/grid_from_python_dict.cc

These definitions are what should be documented for Python embedding. If there are additional grids MET supports that are not included here, then we need to probably align the Python embedding support with MET support so that we don't have to document these twice.

**Comment by DanielAdriaansen** [comment]
Is this sufficient?
https://dtcenter.github.io/MET/Users_Guide/appendixF.html#python-embedding-for-2d-data

**Comment by JohnHalleyGotway** [comment]
@DanielAdriaansen can you please take a look at this issue to see if the work is done? And if so, please close it.

**Comment by JohnHalleyGotway** [comment]
@JohnHalleyGotway and @DanielAdriaansen discussed this on 4/30/21 and agree that the existing documentation in [Appendix F](https://met.readthedocs.io/en/develop/Users_Guide/appendixF.html) describes the grid definition components well for each supported projection. No additional work is required at this time. However, when support for additional projections is added to MET, the documentation should be updated at that time.
