### ISSUE TITLE
Add error message for Xarray pickling.

### ISSUE THREAD

**Issue by DanielAdriaansen** [dtcenter/MET#1472]
## Describe the Problem ##
Here: https://github.com/dtcenter/MET/blob/2c9ae440a84024fbf62caa64c1b747f9a912236f/met/src/libcode/vx_data2d_python/python_dataplane.cc#L437

we exit(1) without printing an error message to the user! We should issue a bug fix to print an error message.

For met-10.0, we should implement support for Xarray Python embedding with pickling. That work is described in #1534 .

### Expected Behavior ###
I expect a warning message instead of MET silently exiting and producing no output.

### Environment ###
Describe your runtime environment:
*1. Machine: kiowa

### To Reproduce ###
To force pickling, set the MET_PYTHON_EXE environment variable. This can be set to any version of Python I think, which just forces invocation of the pickling logic in MET which is necessary to reproduce the error.
`export MET_PYTHON_EXE=/path/to/python`

Call a test script I wrote for Xarray Python embedding
`/usr/local/met-9.1/bin/plot_data_plane PYTHON_XARRAY testXR.ps 'name="/home/dadriaan/projects/remote/read_ascii_xarray.py /home/dadriaan/git/met/met/data/python/fcst.txt FCST";' -title "Testing" -v 10`

### Relevant Deadlines ###
NONE

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones
- [ ] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **master_\<Version>**.
Branch name:  `bugfix_<Issue Number>_master_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **master_\<Version>** and link the pull request to this issue.
Pull request: `bugfix <Issue Number> master_<Version> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch and link the pull request to this issue.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Committed minor tweaks to log messages in python_dataplane.cc directly to the main_v9.1 and develop branches. Note that this does not follow best practices of submitting PR's for code changes.
