### ISSUE TITLE
Move README and README_TC contents to Sphinx

### ISSUE THREAD

**Issue by jprestop** [dtcenter/MET#1474]
This is a sub-issue of #1455 

## Describe the Sub-Issue ##
We currently have lots of details about the MET config file formatting and options that live in the data/config/README file (https://github.com/dtcenter/MET/blob/master_v9.1/met/data/config/README).  

This README originated back when the MET User's Guide was a Word doc that lived on Tressa's machine and the engineers could not easily/reliably update it with the many, many config file details. In addition, a text file is easier to read/search than a Word doc on a Linux system. 

And that README remained through the transition to Lyx since the Lyx files were also not very human-readable.

Now that we've transitioned to Sphinx with .rst files, it seems both reasons for that README file have now disappeared. Engineers can easily update the ascii content in .rst files and .rst files are very human-readable on Linux machines.

We are currently do a literal include of these README files in data_io.rst. But that results in somewhat clunky formatting and we can't reference specific lines directly. Migrate the content of data/config/README and data/config/README_TC into new files in the docs/Users_Guide directory and replace data/config/README with a sentence pointing users to the new location.

Rename README.rst and README_TC.rst to config_options.rst and config_options_tc.rst, then delete section 3.5.1 and 3.5.2 and then have Chapter 4 = "Configuration File Overview" and Chapter 5 = "Tropical Cyclone Configuration Options".

### Time Estimate ###
1 to 3 days of work.

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required (Julie Prestopnik)
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones
- [x] Select **milestone**

**Comment by JohnHalleyGotway** [comment]
Many of the default MET config files in met/data/config have a line at the top similar to the following:
```
// For additional information, see the MET_BASE/config/README file.
```
or
```
// For additional information, see the MET_BASE/config/README_TC file.
```

After README and README_TC are moved to the User's Guide, please replace these comments with a link to the right chapter of the User's Guide.

**Comment by jprestop** [comment]
Thanks, John.  I forgot about this before approving the pull request.  I'll go back in and do those shortly.

**Comment by jprestop** [comment]
Will need to remove references to README_TC from  met/data/config/Makefile.am.  Also, remember to replace the comments in the default MET config files in met/data/config to add links to the README and README_TC files before the next pull request.

**Comment by jprestop** [comment]
A pull request was submitted and merged into develop.  Closing issue.
