### ISSUE TITLE
Complete support for Python Xarray embedding.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1534]
## Describe the Problem ##

I am splitting issue MET #1472 down into 2 pieces: 1 bugfix (#1472) and 1 enhancement (this issue). By the time we work on this issue, #1472 should have already been resolved.

Here: https://github.com/dtcenter/MET/blob/2c9ae440a84024fbf62caa64c1b747f9a912236f/met/src/libcode/vx_data2d_python/python_dataplane.cc#L437

we exit(1) without printing an error message to the user! We should issue a bug fix to print an error message, and then implement the support for this section (Xarray Python embedding with pickling) for v10.0.

### Expected Behavior ###
I expect a warning message instead of MET silently exiting and producing no output.

### Environment ###
Describe your runtime environment:
*1. Machine: kiowa

### To Reproduce ###
To force pickling, set the MET_PYTHON_EXE environment variable. This can be set to any version of Python I think, which just forces invocation of the pickling logic in MET which is necessary to reproduce the error.
`export MET_PYTHON_EXE=/path/to/python`

Call a test script I wrote for Xarray Python embedding
`/usr/local/met-9.1/bin/plot_data_plane PYTHON_XARRAY testXR.ps 'name="/home/dadriaan/projects/remote/read_ascii_xarray.py /home/dadriaan/git/met/met/data/python/fcst.txt FCST";' -title "Testing" -v 10`

### Relevant Deadlines ###
NONE

### Funding Source ###
2791541

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Review **projects** and select relevant **Repository** and **Organization** ones
- [ ] Select **milestone**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above.
- [ ] Fork this repository or create a branch of **master_\<Version>**.
Branch name:  `bugfix_<Issue Number>_master_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **master_\<Version>** and link the pull request to this issue.
Pull request: `bugfix <Issue Number> master_<Version> <Description>`
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch and link the pull request to this issue.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
- [ ] Close this issue.

**Comment by DanielAdriaansen** [comment]
@davidfillmore while doing some other work, I prototyped a "read_xarray_python.py" script based on the "read_numpy_python.py" script already in MET. You can view that script on kiowa:/home/dadriaan/projects/remote/read_xarray_python.py. There's also some information in kiowa:/home/dadriaan/projects/remote/remote_demo.py near the bottom where I conform the attributes of the Xarray DataArray object to the MET standards which may be useful and is related to #1470.

**Comment by dwfncar** [comment]
write_pickle_dataplane.py fails on system module imort
_import importlib.util_
System path issue?

**Comment by dwfncar** [comment]
write_pickle_dataplane is run by the user's python,
designated by MET_PYTHON_EXE.
This must be python 3 and have the importlib module available.

**Comment by dwfncar** [comment]
Added read_ascii_xarray to met/scripts/python.
This script currently fails within write_pickle_dataplane with module 'read_ascii_xarray' has no attribute 'atttrs'.
