### ISSUE TITLE
Fix Grid-Diag bug when reading the same variable name from multiple data sources.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1694]
## Describe the Problem ##
This is a bug in Grid-Diag reported via met-help by the UK MetOffice:
https://rt.rap.ucar.edu/rt/Ticket/Display.html?id=97766

When reading the same variable name from two input data sources, the resulting joint 2D histogram is correct, but the 1D histograms are exactly the same in the output. When changing the variable name for one of the data sources to something else, then the 1D histograms are no longer duplicated. I suspect that this issue is related to the same variable name being used in both input data sources. The code is likely keeping track of the histogram using some string and that's the source of the confusion. Recommend looking there to debug.

Recommend making two more changes for this as well:
- Update the grid_diag log messages to report the set_attr_name/set_attr_level strings instead of the requested variable name/level. If the user has provided name/level overrides, we should report them in the log messages.
- I also found that running with a very small number of bins (10 and 5), some of the resulting histogram counts were not initialized to 0. So we got bogus output values! Should also find/fix that issue.

### Expected Behavior ###
Grid-Diag should produce the same 1D histograms whether the input data is run separately for each data source or once for both. Be sure to add a new unit test which reproduces this bug and verifies that it is fixed.

### Environment ###
Describe your runtime environment:
*1. Machine: reproduced on kiowa*
*2. OS: Linux*
*3. Software version number(s): MET version 9.1*

### To Reproduce ###
Describe the steps to reproduce the behavior:
*1. On 'kiowa'*
*2. Run grid_diag:*
```
cd /d1/projects/MET/MET_Help/mittermaier_data_20210215
/d1/projects/MET/MET_releases/met-9.1.1/bin/grid_diag \
-data glosea_2019060100_d001_001.nc -data gpm_2019060100_2019060200.nc \
-config GridDiag.glosea -out grid_diag_joint.nc -v 3 -log run_gd.log 
ncdump grid_diag_joint.nc > grid_diag_joint.ncdump
```
*3. Inspect grid_diag_joint.ncdump*
*4. Note that the counts for hist_glosea_precip_sfc and hist_gpm_precip_sfc are duplicated!*

### Relevant Deadlines ###
met-10.0.0

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: John HG
- [x] Select **scientist(s)** or **no scientist** required: Marion

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to relevant bugfix version

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts.

## Bugfix Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>_main_<Version>_<Description>`
- [x] Fix the bug and test your changes.
- [x] Add/update log messages for easier debugging.
- [x] Add/update unit tests.
- [x] Add/update documentation.
- [x] Push local changes to GitHub.
- [x] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [x] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [x] Iterate until the reviewer(s) accept and merge your changes.
- [x] Delete your fork or branch.
- [x] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
- [x] Close this issue.

**Comment by JohnHalleyGotway** [comment]
This bug is actually present in the existing unit_grid_diag.xml test output:
```
ncdump -v hist_FCST_APCP_A06 grid_diag_APCP_06_FCST_OBS.nc
ncdump -v hist_OBS_APCP_A06 grid_diag_APCP_06_FCST_OBS.nc
```
They have identical counts, which is not correct:
```
hist_FCST_APCP_A06 = 170628, 1427, 1144, 786, 532, 401, 285, 283, 221, 241, 
    192, 181, 180, 139, 112, 98, 87, 66, 77, 84, 70, 49, 34, 42, 23, 21, 10, 
    5, 5, 2, 3, 2, 4, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ;
 hist_OBS_APCP_A06 = 170628, 1427, 1144, 786, 532, 401, 285, 283, 221, 241, 
    192, 181, 180, 139, 112, 98, 87, 66, 77, 84, 70, 49, 34, 42, 23, 21, 10, 
    5, 5, 2, 3, 2, 4, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ;
```
So this fix will change the NB output.

**Comment by JohnHalleyGotway** [comment]
Will also fix this bug in the main_v9.1 branch for inclusion in a v9.1.2 bugfix release.

**Comment by mpm-meto** [comment]
Tested GridDiag in MET11beta4 and seems to work as intended with the variable name changes etc. Thanks!

**Comment by JohnHalleyGotway** [comment]
@mpm-meto, thanks for confirming that this works as expected. Glad to hear it!
