### ISSUE TITLE
Fix pb2nc segfault when deriving PBL

### ISSUE THREAD

**Issue by jprestop** [dtcenter/MET#1715]
## Describe the Problem ##

Mallory Row brought to our attention that when testing with her grid-to-obs use cases, she was getting segfaults with PB2NC.  She saw in the MET 9.1.2 release notes that there was a fix for this (https://github.com/dtcenter/MET/pull/1622), however she wasn't using the -index option like the release notes stated. 

Mallory put together a test case for this on the both the Dell and the Cray (WCOSS).  On the Dell, the case segfaults with 9.1, but not 9.1.2. On the Cray, it segfaults with both versions.
Dell: /gpfs/dell2/emc/verification/noscrub/emc.metplus/for_nco/met/met_test/case_6
Cray: /gpfs/hps3/emc/meso/noscrub/emc.metplus/for_nco/met/met_test/case_6
In README.txt is the command.

She turned up the verbosity to 5. The segfault came after this bit:
```
DEBUG 5: process_pbfile() PBL: excluded 0-th level record: T=-9999, U=-9999, V=-9999, Q=100000, Z=47 valid_time: 20210311_000000 ADPUPA 72363
DEBUG 5: process_pbfile() PBL: excluded 1-th level record: T=-9999, U=-9999, V=-9999, Q=92500, Z=722 valid_time: 20210311_000000 ADPUPA 72363
DEBUG 5: process_pbfile() Reverse levels
DEBUG 5: interpolate_by_pressure() interpolated count: 2
DEBUG 4: compute_pbl() interpolate Z (HGT)
DEBUG 5: interpolate_by_pressure() interpolated count: 4
DEBUG 4: compute_pbl() interpolate Q (SPFH)
DEBUG 5: process_pbfile() Reverse levels
Segmentation fault (core dumped)

```
She took "D_PBL" of the list to get variables from the prepbufr file, and she got no segfault, but with "D_PBL" in it segfaults.

### Expected Behavior ###
Segfaults are NEVER acceptable and always mean that there's some additional error checking we should add to the code.

### Environment ###
Describe your runtime environment:
*1. Machine: WCOSS Dell and Cray*
*2. OS: *
*3. Software version number(s): METv9.1 and METv9.1.2*

### To Reproduce ###
Describe the steps to reproduce the behavior:
*1. Get data from WCOSS once available*
*2. Run using the command in README.txt*
*3. See if the seg fault is reproducible on a local machine.  If not, text on WCOSS.*

### Relevant Deadlines ###
ASAP

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to relevant bugfix version

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>_main_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
- [ ] Close this issue.

**Comment by malloryprow** [comment]
Problem station: D_PBL at station ID 72493 from files sent to FTP

For 9.1.1, pb2nc seg-faulted on both the WCOSS Dell and Cray.
For 9.1.2, pb2nc seg-faulted on Cray but ran fine on the Dell.

The segfault occurs in the interpolate_pqtzuv() function, called by combine_tqz_and_uv(), and called by merge_records().

Recommend that we compile using the Intel -ftrapuv compiler option to check for uninitialized variables.

We could also add more debugging information into 9.1.2 or recompile 9.1.2 with debug options enabled.

**Comment by malloryprow** [comment]
Log files
[good_dell_912.log](https://github.com/dtcenter/MET/files/6158642/good_dell_912.log)
[bad_cray_91.log](https://github.com/dtcenter/MET/files/6158644/bad_cray_91.log)

**Comment by hsoh-u** [comment]
Thank you for the log files. The problem happens when there are no overlapping (by pressure) at TQZ records and UV records.
- 1 TQZ record at pressure 101300.
- The UV records are between 97670 and 510.
