### ISSUE TITLE
Fix user python embedding to handle the fill value correctly

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1753]
## Describe the Problem ##
This is an issue @j-opatz ran into when trying to use python embedding to pass data into MET for NOAA/CPC. These scripts worked fine in met-10.0.0_beta3 but was broken by PR #1720 which merged changes for MET issues #1319. The python embedding script works fine when MET_PYTHON_EXE is NOT set, but produces different output when it is set. The issue is that the temporary NetCDF output created by write_tmp_dataplane.py does no encode the bad data value correctly.

### Expected Behavior ###
If python embedding works without MET_PYTHON_EXE set, rerunning with it set should produce the same result.

### Environment ###
Describe your runtime environment:
*1. Machine: NCAR Linux project machine kiowa*
*2. OS: (e.g. RedHat Linux, MacOS)*
*3. Software version number(s): issue appears after PR #1720*

### To Reproduce ###
Describe the steps to reproduce the behavior:
*1. On kiowa, run the following commands:*
```
sh
PDP=/d1/projects/MET/MET_regression/develop/NB`date +%Y%m%d`/MET-develop/met/bin/plot_data_plane 
export fcst_file=/d1/projects/CPC_data/input/precip_poe_fcsts/2019/08/07/gefs-legacy-00z_rfcst-cal_precip_20190807_week2.nc
$PDP PYTHON_NUMPY plot_met_python.ps 'name="./poe_fcst_embedded.py ${fcst_file}:33";' -v 4
export MET_PYTHON_EXE=/usr/local/python3/bin/python3
$PDP PYTHON_NUMPY plot_user_python.ps 'name="./poe_fcst_embedded.py ${fcst_file}:33";' -v 4
```
*2. Note the difference in max values listed in the log messages:*
```
DEBUG 4: Data plane information:
DEBUG 4:       plane min: 0.364983
DEBUG 4:       plane max: 0.814893
...
DEBUG 4: Data plane information:
DEBUG 4:       plane min: 0.364983
DEBUG 4:       plane max: 9.96921e+36
```
*3. Look at the plots below and note that the range of valid data values differ:*
![plot_met_python](https://user-images.githubusercontent.com/21087144/114922658-2b0ac900-9de9-11eb-9629-7ab1b2696c98.png)
![plot_user_python](https://user-images.githubusercontent.com/21087144/114922667-2cd48c80-9de9-11eb-9a7b-93299826a485.png)

### Relevant Deadlines ###
Fix for met-10.0.0_beta5

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Review **projects** and select relevant **Repository** and **Organization** ones or add "alert:NEED PROJECT ASSIGNMENT" label
- [x] Select **milestone** to relevant bugfix version

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts.

## Bugfix Checklist ##
See the [METplus Workflow](https://dtcenter.github.io/METplus/Contributors_Guide/github_workflow.html) for details.
- [x] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [x] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>_main_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)**, **Project(s)**, **Milestone**, and **Linked issues**
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
- [ ] Close this issue.

**Comment by j-opatz** [comment]
The NB was tested this morning with a use case that had previously failed with the initial change in temporary netCDF logic. It now runs successfully and produces the output that came in the beta3 release.
