### ISSUE TITLE
Stat-Analysis consumes too much memory.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#1875]
## Describe the Problem ##
This issue arose via METplus Discussions dtcenter/METplus#1076. @lindsayrblank reported the problem and provided data and Stat-Analysis commands to demonstrate the problem.

The void ClimoCDFInfo::set_cdf_ta(int n_bin, bool &center) function fails to initialize the cdf_ta array. This is called once for each "case" (i.e. OBS_SID + FCST_VAR) encountered by Stat-Analysis. And each time, that array grows by 21 elements. That's what's hogging all the memory.

Recommend fixing this in the main_v10.0 branch with a one-line fix.
Recommend fixing this in the develop branch with that same one-line fix but also add a DEBUG(3) log message for each new "case" this is created, like this:
```
DEBUG 3: [4756] Adding new case for key = CWBZ:TMP
```
Also consider re-implementing the NumArray class as an STL vector since it's default memory allocation is 1000 elements. Lindsay's jobs use less than 50 of those 1000 array elements.

### Expected Behavior ###
The job listed below should complete in a reasonable amount of time and use MUCH less than 20GB of memory.

### Environment ###
Describe your runtime environment:
*1. Machine: Mac Laptop*
*2. OS: MacOS*
*3. Software version number(s): MET version 10.0*

### To Reproduce ###
Describe the steps to reproduce the behavior:
Use this input file to run the job below:
[TMP_72hr.txt](https://github.com/dtcenter/MET/files/6994887/TMP_72hr.txt)
```
stat_analysis -lookin TMP_72hr.txt -job aggregate_stat -line_type MPR -out_line_type CNT -out_stat TMP_72hr_output.stat -by OBS_SID,FCST_VAR -set_hdr VX_MASK OBS_SID -set_hdr DESC CASE -v 3 
```
That job consumes well over 20GB of memory on my Mac laptop!

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required: John HG
- [x] Select **scientist(s)** or **no scientist** required: no scientist needed

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Organization** level **Project** for support of the current coordinated release
- [x] Select **Repository** level **Project** for development toward the next official release or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next bugfix version

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts.

## Bugfix Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>_main_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Organization** level software support **Project** for the current coordinated release
Select: **Milestone** as the next bugfix version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Met with @lindsayrblank on 8/27/2021 to further discuss memory usage issues. Even after fixing this bug, her Stat-Analysis configuration eventually leads to an out-of-memory error. To test further, I restored the bugfix_1875_main_v10.0_memory branch and changed the default NumArray allocation increment from 1000 down to 100. I enabled that branch to be built by DockerHub and pushed up the changes.

To retrieve that branch for testing run:
```
docker pull dtcenter/met:bugfix_1875
```
@lindsayrblank will test this branch and report back on the reduction in memory usage, if any. My expectation is that the memory usage will be reduced by up to 90%. If that really is the case, I recommend that we reimplement the NumArray class based on an STL class (perhaps vector or array?) instead of managing chunks of memory ourselves.

**Comment by lindsayrblank** [comment]
@JohnHalleyGotway I performed tests using the bugfix_1875_main Docker image. The results are encouraging with memory reduction of ~75%. 

Test 1: pre-bugfix: 26.2G, 13:52 runtime; post-bugfix: 6.33G, 13:33 runtime
Test 2: pre-bugfix: 51.9G, 26:56 runtime; post-bugfix: 12.38G, 22:13 runtime

**Comment by JohnHalleyGotway** [comment]
@lindsayrblank thanks for getting back to me with these details. I referenced this in this new GitHub issue for optimizing the NumArray class: dtcenter/MET#1899
