### ISSUE TITLE
Update the copyright year of the source code to 2022.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#2013]
## Describe the Task ##
Update the copyright year within the source code to 2022.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
Split 2792541 and 2702691

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by davidalbo** [comment]
Notes:
This command seems to work:
find . -type f -exec sed -i 's/Copyright UCAR (c) 1992 - 2021/Copyright UCAR (c) 1992 - 2022/g' {} \\;

assuming it is the only pattern in the MET repo that needs changing.  Will look deeper to see if so.

To verify:
find . -type f -exec grep 'Copyright UCAR (c) 1992 - 2021' {} \\;   before should list everything, after empty
find . -type f -exec grep 'Copyright UCAR (c) 1992 - 2022' {} \\;   before should be empty, after list everything

**Comment by davidalbo** [comment]
MET/met/README has  a different copyright:    Copyright 2021, UCAR/NCAR, NOAA, and CSU/CIRA
change it?

**Comment by JohnHalleyGotway** [comment]
@TaraJensen and @bonnystrong can you please advise on this question?

The MET source code files include the following copyright at the top of each file:
```
// *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
// ** Copyright UCAR (c) 1992 - 2021
// ** University Corporation for Atmospheric Research led(UCAR)
// ** National Center for Atmospheric Research (NCAR)
// ** Research Applications Lab (RAL)
// ** P.O.Box 3000, Boulder, Colorado, 80307-3000, USA
// *=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*=*
```

The top-level MET README file includes:
```
Copyright 2021, UCAR/NCAR, NOAA, and CSU/CIRA
```
But please see [this line](https://github.com/dtcenter/MET/blob/5e1f551d86fcb5b731e3a83c0b043dbd7ef3c7aa/met/README#L5) for the complete statement.

Options are:
1. Leave everything as-is and just update [this line](https://github.com/dtcenter/MET/blob/5e1f551d86fcb5b731e3a83c0b043dbd7ef3c7aa/met/README#L5) by changing 2021 to 2022.
2. Change the copyright statement in the README file to be more consistent with the code (1 place).
3. Change the copyright statement in the source code files to be more consistent with the README file (912 places).

**Comment by JohnHalleyGotway** [comment]
@davidalbo please also update to 2022 in met/docs/users_guide/index.rst.

**Comment by jprestop** [comment]
@JohnHalleyGotway We discovered that met/docs/users_guide/index.rst had already been updated, so no work is needed on that file for this task.

**Comment by davidalbo** [comment]
README was modified to agree with that in met/docs/users_guide/index.rst to include more groups.

Copyright 2022, UCAR/NCAR, NOAA, CSU/CIRA, and CU/CIRES
