### ISSUE TITLE
Automate calls to the SonarQube static code analysis tool in the nightly build

### ISSUE THREAD

**Issue by hsoh-u** [dtcenter/MET#2020]
*Replace italics below with details for this issue.*

## Describe the New Feature ##
Add script to run SonarQube scanner

### Acceptance Testing ###
*List input data types and sources.*
*Describe tests required for new functionality.*

Create the scripts of SonarQube and add to the crontab for the night build under "met_test" account.

### Time Estimate ###
*Estimate the amount of work required here.*
4 hours

### Sub-Issues ###
Consider breaking the new feature down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
2771021

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## New Feature Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by hsoh-u** [comment]
Build problem at src/basic/vx_math on seneca:
hsoh@seneca:/d1/personal/hsoh/git/release/MET_tag_v10.1.0-beta5/met/src/basic/vx_math$ make
make: *** No rule to make target 'viewgravity_to_string.cc', needed by 'libvx_math_a-viewgravity_to_string.o'.  Stop.


at kiowa:
/d1/personal/hsoh/git/pull_request/MET_feature_1844_python_embedding/met/src/basic/enum_to_string/enum_to_string -concat_string affine.h

enum_to_string:  Making header file "viewgravity_to_string.h"
enum_to_string:  Making source file "viewgravity_to_string.cc"
g++ -DHAVE_CONFIG_H -I. -I../../..  -I../../../src/basic/vx_cal -I../../../src/basic/vx_config -I../../../src/basic/vx_log -I../../../src/basic/vx_math -I../../../src/basic/vx_util -I../../../src/libcode/vx_afm -I../../../src/libcode/vx_analysis_util -I../../../src/libcode/vx_color -I../../../src/libcode/vx_data2d -I../../../src/libcode/vx_data2d_factory -I../../../src/libcode/vx_data2d_grib -I../../../src/libcode/vx_data2d_grib2 -I../../../src/libcode/vx_data2d_nccf -I../../../src/libcode/vx_data2d_nc_met -I../../../src/libcode/vx_data2d_nc_pinterp -I../../../src/libcode/vx_data2d_python -I../../../src/libcode/vx_python3_utils -I../../../src/libcode/vx_geodesy -I../../../src/libcode/vx_gis -I../../../src/libcode/vx_gnomon -I../../../src/libcode/vx_grid -I../../../src/libcode/vx_gsl_prob -I../../../src/libcode/vx_nav -I../../../src/libcode/vx_nc_obs -I../../../src/libcode/vx_nc_util -I../../../src/libcode/vx_pb_util -I../../../src/libcode/vx_plot_util -I../../../src/libcode/vx_pointdata_python -I../../../src/libcode/vx_ps -I../../../src/libcode/vx_pxm -I../../../src/libcode/vx_render -I../../../src/libcode/vx_regrid -I../../../src/libcode/vx_shapedata -I../../../src/libcode/vx_solar -I../../../src/libcode/vx_statistics -I../../../src/libcode/vx_stat_out -I../../../src/libcode/vx_summary -I../../../src/libcode/vx_time_series -I../../../src/libcode/vx_series_data -I../../../src/libcode/vx_tc_util -fopenmp -I/usr/local/netcdf-4.7.0/gcc-6.3.0/include -I/usr/local/hdf5-1.8.20/include -I/usr/local/include -I../../basic/vx_log -I../../basic/vx_util -I/var/autofs/mnt/linux-amd64/debian/stretch/local/met-python3/include/python3.7m -I/d1/projects/MET/MET_releases/external_libs/gnu_6.3.0/include -I/usr/local/hdf4-4.2.13/include/hdf -I/usr/local/hdf-eos2-19v1/include -I/usr/include/cairo -I/usr/include/freetype2 -DBLOCK4 -DWITH_GRIB2 -DWITH_PYTHON -DMET_BASE="\"/d1/personal/hsoh/git/pull_request/MET_feature_1844_python_embedding/met/share/met\""  -g -DUNDERSCORE -fPIC -D__64BIT__ -MT libvx_math_a-viewgravity_to_string.o -MD -MP -MF .deps/libvx_math_a-viewgravity_to_string.Tpo -c -o libvx_math_a-viewgravity_to_string.o `test -f 'viewgravity_to_string.cc' || echo './'`viewgravity_to_string.cc
anlib libvx_math.a

**Comment by hsoh-u** [comment]
It's resolved after sourcing /d1/projects/MET/MET_regression/MET-develop/scripts/environment/development.seneca.

**Comment by JohnHalleyGotway** [comment]
@hsoh-u glad to hear it. FYI, the "MET_DEVELOPMENT" environment variable needs to be set to turn on calls to that enum_to_string code. So I suspect that's the change that fixed it.
