### ISSUE TITLE
Investigate nightly build output wind direction differences caused by machine precision.

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/MET#2027]
Note that this issue originally indicated that issues in Grid-Stat and Madis2NC should be investigated. However, the Madis2NC details were moved to a separate issue #2028 that @hsoh-u is investigating.

There are differences in the output generated from the MET-develop-ref data between machines. This is likely due to something different with an external dependency.

I copied data from the nightly builds from seneca and kiowa into a directory on seneca and ran the comp_dir.sh script.

Files are under:
/d1/personal/mccabe/kiowa_vs_seneca

> comp_dir_grid_stat.log
> comp_dir_madis2nc.log

These log files were generated by running the following commands:

`~mccabe/MET/test/bin/comp_dir.sh /d1/personal/mccabe/kiowa_vs_seneca/kiowa/NB20220125/MET-develop-ref/test_output/grid_stat /d1/personal/mccabe/kiowa_vs_seneca/seneca/NB20220125/MET-develop-ref/test_output/grid_stat &> comp_dir_grid_stat.log`

> 
> COMPARING grid_stat_GFS_FOURIER_240000L_20120410_000000V_pairs.nc
> file1: /d1/personal/mccabe/kiowa_vs_seneca/kiowa/NB20220125/MET-develop-ref/test_output/grid_stat/grid_stat_GFS_FOURIER_240000L_20120410_000000V_pairs.nc
> file2: /d1/personal/mccabe/kiowa_vs_seneca/seneca/NB20220125/MET-develop-ref/test_output/grid_stat/grid_stat_GFS_FOURIER_240000L_20120410_000000V_pairs.nc
> passed numerical var CLIMO_MEAN_HGT_P500_FULL
> passed numerical var CLIMO_MEAN_HGT_P500_FULL_WV1_0-3.
> ..
> passed numerical var FCST_HGT_P500_FULL
> passed numerical var FCST_HGT_P500_FULL_WV1_0-3
> **ERROR: found     2 differences in var FCST_HGT_P500_FULL_WV1_0-72            - max abs: 0.0004882812**
> passed numerical var FCST_HGT_P500_FULL_WV1_10-20
> ...
> 
> COMPARING grid_stat_GFS_FOURIER_240000L_20120410_000000V.stat
> file1: /d1/personal/mccabe/kiowa_vs_seneca/kiowa/NB20220125/MET-develop-ref/test_output/grid_stat/grid_stat_GFS_FOURIER_240000L_20120410_000000V.stat
> file2: /d1/personal/mccabe/kiowa_vs_seneca/seneca/NB20220125/MET-develop-ref/test_output/grid_stat/grid_stat_GFS_FOURIER_240000L_20120410_000000V.stat
> ERROR: found     8 differences in row type CNT          column FBAR          - max abs: 0.00000000000000008326
> ERROR: found     8 differences in row type CNT          column OBAR          - max abs: 0.00000000000000002775
> ERROR: found     8 differences in row type CNT          column ME            - max abs: 0.000000000000000013115
> ERROR: found     8 differences in row type CNT          column ME2           - max abs: 0.0000000000000000000000000000000022368
> ERROR: found     8 differences in row type SAL1L2       column FABAR         - max abs: 0.00000000000000006939
> ERROR: found     8 differences in row type SAL1L2       column OABAR         - max abs: 0.0000000000000000763
> ERROR: found     8 differences in row type SL1L2        column FBAR          - max abs: 0.00000000000000008326
> ERROR: found     8 differences in row type SL1L2        column OBAR          - max abs: 0.00000000000000002775
> ERROR: found     2 differences in row type VAL1L2       column UFABAR        - max abs: 0.0000000000000000001999
> ERROR: found     2 differences in row type VAL1L2       column VFABAR        - max abs: 0.000000000000000003469
> ERROR: found     2 differences in row type VAL1L2       column UOABAR        - max abs: 0.000000000000000001735
> ERROR: found     2 differences in row type VAL1L2       column VOABAR        - max abs: 0.00000000000000000165
> ERROR: found     2 differences in row type VCNT         column FBAR_SPEED    - max abs: 0.000000000000000004651
> ERROR: found     2 differences in row type VCNT         column OBAR_SPEED    - max abs: 0.000000000000000001861
> ERROR: found     2 differences in row type VCNT         column VDIFF_SPEED   - max abs: 0.000000000000000003135
> ERROR: found     2 differences in row type VCNT         column SPEED_ERR     - max abs: 0.000000000000000002968
> ERROR: found     2 differences in row type VCNT         column SPEED_ABSERR  - max abs: 0.000000000000000002968
> **ERROR: found     2 differences in row type VCNT         column DIR_ERR       - max abs: 2.3507
> ERROR: found     2 differences in row type VCNT         column DIR_ABSERR    - max abs: 2.3507**
> ERROR: found     2 differences in row type VL1L2        column UFBAR         - max abs: 0.00000000000000000094864
> ERROR: found     2 differences in row type VL1L2        column VFBAR         - max abs: 0.000000000000000005204
> ERROR: found     2 differences in row type VL1L2        column UOBAR         - max abs: 0.000000000000000000867
> ERROR: found     2 differences in row type VL1L2        column VOBAR         - max abs: 0.000000000000000001952
> 
> SUMMARY for non-bootstrap numerical values
> \# comparisons: 1575
> \# differences: 94
>        Min.: -2.3507
>     1st Qu.: -1.844e-18
>      Median: -2.4458e-19
>        Mean: -0.05001489
>     3rd Qu.: 1.2587e-18
>        Max.: 1.48229
> 
> **ERROR: failed tests for CNT: num
> ERROR: failed tests for SAL1L2: num
> ERROR: failed tests for SL1L2: num
> ERROR: failed tests for VAL1L2: num
> ERROR: failed tests for VCNT: num
> ERROR: failed tests for VL1L2: num**

`~mccabe/MET/test/bin/comp_dir.sh /d1/personal/mccabe/kiowa_vs_seneca/kiowa/NB20220125/MET-develop-ref/test_output/madis2nc /d1/personal/mccabe/kiowa_vs_seneca/seneca/NB20220125/MET-develop-ref/test_output/madis2nc &> comp_dir_madis2nc.log`

>
> COMPARING profiler_2012040912_F000.nc
> file1: /d1/personal/mccabe/kiowa_vs_seneca/kiowa/NB20220125/MET-develop-ref/test_output/madis2nc/profiler_2012040912_F000.nc
> file2: /d1/personal/mccabe/kiowa_vs_seneca/seneca/NB20220125/MET-develop-ref/test_output/madis2nc/profiler_2012040912_F000.nc
> ERROR: NetCDF headers differ:
> 11c11
> \<       nobs_qty = 2 ;
> ---
> \>       nobs_qty = 1 ;

## Describe the Task ##
Investigate these differences and create a GitHub issue if a fix to the source code would prevent these differences. If changes to the external libraries used to build MET on seneca resolve these differences, then document those changes on this issue.

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by hsoh-u** [comment]
madis2nc is separated and created a new issue [https://github.com/dtcenter/MET/issues/2028](https://github.com/dtcenter/MET/issues/2028)

**Comment by JohnHalleyGotway** [comment]
From @hsoh-u on 2/8/2022:

There are five DIR_ERR values. It's computed from vf_bar, uo_bar, uf_bar, and vo_bar values.
The last two  did not match (with a difference of 2.x). It was caused by a different vf_bar, uo_bar, uf_bar, and vo_bar values. They are close to 0 (D.DDDe-17).

Seneca:
```
DEBUG 9: VL1L2Info::calc_ncep_stats() -> DIR_ERR=0.1631764381 : vf_bar=0.04513603426, uo_bar=6.606426793, uf_bar=6.57913798, vo_bar=0.02650780019
DEBUG 9: VL1L2Info::calc_ncep_stats() -> DIR_ERR=0.1631764381 :  vf_bar=0.04513603426, uo_bar=6.606426793, uf_bar=6.57913798, vo_bar=0.02650780019
DEBUG 9: VL1L2Info::calc_ncep_stats() -> DIR_ERR=0.1631764381 :  vf_bar=0.04513603426, uo_bar=6.606426793, uf_bar=6.57913798, vo_bar=0.02650780019
DEBUG 9: VL1L2Info::calc_ncep_stats() -> DIR_ERR=13.97656972 :  vf_bar=-3.005226988e-17, uo_bar=1.435941868e-17, uf_bar=1.645432968e-17, vo_bar=-5.463701323e-17
DEBUG 9: VL1L2Info::calc_ncep_stats() -> DIR_ERR=-0.7288621685 : vf_bar=-4.763382423e-17, uo_bar=2.573841959e-18, uf_bar=1.505336366e-18, vo_bar=-5.804548043e-17
```

Kiowa:
```
DEBUG 9: VL1L2Info::calc_ncep_stats() -> DIR_ERR=0.1631764381 : vf_bar=0.04513603426, uo_bar=6.606426793, uf_bar=6.57913798, vo_bar=0.02650780019
DEBUG 9: VL1L2Info::calc_ncep_stats() -> DIR_ERR=0.1631764381 : vf_bar=0.04513603426, uo_bar=6.606426793, uf_bar=6.57913798, vo_bar=0.02650780019
DEBUG 9: VL1L2Info::calc_ncep_stats() -> DIR_ERR=0.1631764381 : vf_bar=0.04513603426, uo_bar=6.606426793, uf_bar=6.57913798, vo_bar=0.02650780019
DEBUG 9: VL1L2Info::calc_ncep_stats() -> DIR_ERR=11.62587282 : vf_bar=-3.525644031e-17, uo_bar=1.349205694e-17, uf_bar=1.64674587e-17, vo_bar=-5.658857714e-17
DEBUG 9: VL1L2Info::calc_ncep_stats() -> DIR_ERR=-2.211154954 : vf_bar=-4.806726687e-17, uo_bar=3.007271365e-18, uf_bar=5.56659465e-19, vo_bar=-5.988862412e-17
```

computing uf_bar & vf_bar:

Xe-08 or Xe-09 values became Xe-17

Seneca:
```
DEBUG 9: VL1L2Info::set -> S1 uf_bar=-2.652644106e-07  vf_bar=-2.071753117e-08, wgt=9.512937595e-05, uf=0.001483803557, vf=0.0002482870117, wgt*uf=1.411533065e-07, wgt*vf=2.361938848e-08
DEBUG 9: VL1L2Info::set -> S2 uf_bar=-1.241111041e-07  vf_bar=-2.071753117e-08, wgt=9.512937595e-05, uf=0.001483803557, vf=0.0002482870117, wgt*uf=1.411533065e-07, wgt*vf=2.361938848e-08
DEBUG 9: VL1L2Info::set -> S3 uf_bar=-1.241111041e-07  vf_bar=2.901857312e-09, wgt=9.512937595e-05, uf=0.001483803557, vf=0.0002482870117, wgt*uf=1.411533065e-07, wgt*vf=2.361938848e-08
DEBUG 9: VL1L2Info::set -> S1 uf_bar=-1.241111041e-07  vf_bar=2.901857312e-09, wgt=9.512937595e-05, uf=0.001304655926, vf=-3.050432438e-05, wgt*uf=1.241111041e-07, wgt*vf=-2.901857342e-09
DEBUG 9: VL1L2Info::set -> S2 uf_bar=1.645432968e-17  vf_bar=2.901857312e-09, wgt=9.512937595e-05, uf=0.001304655926, vf=-3.050432438e-05, wgt*uf=1.241111041e-07, wgt*vf=-2.901857342e-09
DEBUG 9: VL1L2Info::set -> S3 uf_bar=1.645432968e-17  vf_bar=-3.005226988e-17, wgt=9.512937595e-05, uf=0.001304655926, vf=-3.050432438e-05, wgt*uf=1.241111041e-07, wgt*vf=-2.901857342e-09
DEBUG 9: VL1L2Info::calc_ncep_stats() -> DIR_ERR=13.97656972 from vf_bar=-3.005226988e-17, uo_bar=1.435941868e-17, uf_bar=1.645432968e-17, vo_bar=-5.463701323e-17
```

kiowa:
```
DEBUG 9: VL1L2Info::set -> S1 uf_bar=-2.652644106e-07  vf_bar=-2.071753117e-08, wgt=9.512937595e-05, uf=0.001483803557, vf=0.0002482870117, wgt*uf=1.411533065e-07, wgt*vf=2.361938848e-08
DEBUG 9: VL1L2Info::set -> S2 uf_bar=-1.241111041e-07  vf_bar=-2.071753117e-08, wgt=9.512937595e-05, uf=0.001483803557, vf=0.0002482870117, wgt*uf=1.411533065e-07, wgt*vf=2.361938848e-08
DEBUG 9: VL1L2Info::set -> S3 uf_bar=-1.241111041e-07  vf_bar=2.901857306e-09, wgt=9.512937595e-05, uf=0.001483803557, vf=0.0002482870117, wgt*uf=1.411533065e-07, wgt*vf=2.361938848e-08
DEBUG 9: VL1L2Info::set -> S1 uf_bar=-1.241111041e-07  vf_bar=2.901857306e-09, wgt=9.512937595e-05, uf=0.001304655926, vf=-3.050432438e-05, wgt*uf=1.241111041e-07, wgt*vf=-2.901857342e-09
DEBUG 9: VL1L2Info::set -> S2 uf_bar=1.64674587e-17  vf_bar=2.901857306e-09, wgt=9.512937595e-05, uf=0.001304655926, vf=-3.050432438e-05, wgt*uf=1.241111041e-07, wgt*vf=-2.901857342e-09
DEBUG 9: VL1L2Info::set -> S3 uf_bar=1.64674587e-17  vf_bar=-3.525644031e-17, wgt=9.512937595e-05, uf=0.001304655926, vf=-3.050432438e-05, wgt*uf=1.241111041e-07, wgt*vf=-2.901857342e-09
DEBUG 9: VL1L2Info::calc_ncep_stats() -> DIR_ERR=11.62587282 from vf_bar=-3.525644031e-17, uo_bar=1.349205694e-17, uf_bar=1.64674587e-17, vo_bar=-5.658857714e-17
```

My quick test (standalone):
The same output values were printed at kiowa and seneca.

```
Input set1:
    uf_bar=-2.434699387e-07;
    vf_bar=-2.519576971e-07;
    wgt=9.512937595e-05;
    uf=0.001546335324;
    vf=0.001141778816;

Input set2:
    uf_bar=-2.43469938731630990579e-07;
    vf_bar=-2.51957697134909476649e-07;
    wgt=9.51293759512937542322e-05;
    uf=1.54633532441387274575e-03;
    vf=1.14177881578629049353e-03;
Input set3:
    uf_bar=-2.43469938732579667480e-07;
    vf_bar=-2.51957697135340139963e-07;
    wgt=9.51293759512937542322e-05;
    uf=1.54633532441387274575e-03;
    vf=1.14177881578629461350e-03;

Output:

Seneca:
   Value of uf_bar =    -9.63680243184389006296e-08   vf_bar =    -1.43340990860990147391e-07  wgt_uf =     1.41153306409800275574e-07 wgt_vf =     2.36193884795113493657e-08
   Value of uf_bar =    -9.63680243086978893873e-08   vf_bar =    -1.43340990914752466754e-07  wgt_uf =     1.41153306409800275574e-07 wgt_vf =     2.36193884795113493657e-08
   Value of uf_bar =    -9.63680243096465662882e-08   vf_bar =    -1.43340990915182733021e-07  wgt_uf =     1.41153306409800275574e-07 wgt_vf =     2.36193884795113493657e-08

kiowa
   Value of uf_bar =    -9.63680243184389006296e-08   vf_bar =    -1.43340990860990147391e-07  wgt_uf =     1.41153306409800275574e-07 wgt_vf =     2.36193884795113493657e-08
   Value of uf_bar =    -9.63680243086978893873e-08   vf_bar =    -1.43340990914752466754e-07  wgt_uf =     1.41153306409800275574e-07 wgt_vf =     2.36193884795113493657e-08
   Value of uf_bar =    -9.63680243096465662882e-08   vf_bar =    -1.43340990915182733021e-07  wgt_uf =     1.41153306409800275574e-07 wgt_vf =     2.36193884795113493657e-08
```

**Comment by JohnHalleyGotway** [comment]
@hsoh-u this actually relates very well to a question raised at this week's METplus NOAA telecon on 2/7/2022. When wind speeds are close to 0, the wind direction is not well-defined. All of these numbers are extremely close to 0. The differences we are seeing in the wind directions and due to differences in the precision of the two different machines.

U/V values very close to 0 with slightly different levels of precision can result in very different wind directions.

In my opinion, the best way to solve this problem is by re-configuring the test to avoid it in the first place.

Recommend modifying [test/config/GridStatConfig_fourier](https://github.com/dtcenter/MET/blob/4a31d4f13fe27e26320eb388a512baaeaa0ed5ff/test/config/GridStatConfig_fourier#L50) like this:
```
-wind_thresh         = [ NA ];
-wind_logic          = UNION;
+wind_thresh         = [ >5.0 ];
+wind_logic          = UNION;
```

That change tells Grid-Stat to only use U/V matched pairs where the forecast wind speed OR observed wind speed exceed 5 m/s. And that should result in either 0 matched pairs (because all points were filtered out) or VL1L2 partial sums that aren't so close to 0.

**Comment by hsoh-u** [comment]
Are the differences acceptable or should the configuration be changed?

Unittest output directories:
- kiowa:/d1/personal/hsoh/git/pull_request/MET_feature_2027_grid_stat_wind_direction
- seneca:/d1/personal/hsoh/git/features/feature_2027_grid_stat_wind_direction/MET/unit_test_output/

Differences between kiowa and seneca:
```
Difference Log file:  seneca:/dev/shm/hsoh/diff/met_comp_20220210_2125.log
Output file: grid_stat/grid_stat_GFS_FOURIER_240000L_20120410_000000V.stat

142:ERROR: found     2 differences in var FCST_HGT_P500_FULL_WV1_0-72            - max abs: 0.0004882812
186:ERROR: found     8 differences in row type CNT          column FBAR          - max abs: 0.00000000000000008326
193:ERROR: found     8 differences in row type CNT          column OBAR          - max abs: 0.00000000000000002775
200:ERROR: found     8 differences in row type CNT          column ME            - max abs: 0.000000000000000013115
207:ERROR: found     8 differences in row type CNT          column ME2           - max abs: 0.0000000000000000000000000000000022368
214:ERROR: found     8 differences in row type SAL1L2       column FABAR         - max abs: 0.00000000000000006939
221:ERROR: found     8 differences in row type SAL1L2       column OABAR         - max abs: 0.0000000000000000763
228:ERROR: found     8 differences in row type SL1L2        column FBAR          - max abs: 0.00000000000000008326
235:ERROR: found     8 differences in row type SL1L2        column OBAR          - max abs: 0.00000000000000002775
253:ERROR: failed tests for CNT: num
254:ERROR: failed tests for SAL1L2: num
255:ERROR: failed tests for SL1L2: num
```

**Comment by JohnHalleyGotway** [comment]
@hsoh-u, yes, those differences are acceptable.
