### ISSUE TITLE
Update the PB2NC configuration to correct the obs_prefbufr_map name as obs_prepbufr_map.

### ISSUE THREAD

**Issue by hsoh-u** [dtcenter/MET#2044]
*Replace italics below with details for this issue.*

## Describe the Problem ##
*Provide a clear and concise description of the bug here.*

The configuration name "obs_prefbufr_map" should be renamed to "obs_prefbufr_map".

- update it in all the config file (under the met and test directories)
- update any "pref" variable names in the MET code base
- update "pref" in the user's guide
- print a warning message alerting the user that the name should be changed to "obs_prepbufr_map" If "obs_prefbufr_map" is present in the config file.
- use it's value instead of "obs_prepbufr_map" if "obs_prefbufr_map" is defined

Will do it for the develop branch, not main_v10.0.

### Expected Behavior ###
*Provide a clear and concise description of what you expected to happen here.*

For the backward compatibility support both "obs_prefbufr_map" and "obs_prefbufr_map".

### Environment ###
Describe your runtime environment:
*1. Machine: (e.g. HPC name, Linux Workstation, Mac Laptop)*
*2. OS: (e.g. RedHat Linux, MacOS)*
*3. Software version number(s)*

### To Reproduce ###
Describe the steps to reproduce the behavior:
*1. Go to '...'*
*2. Click on '....'*
*3. Scroll down to '....'*
*4. See error*
*Post relevant sample data following these instructions:*
*https://dtcenter.org/community-code/model-evaluation-tools-met/met-help-desk#ftp*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Organization** level **Project** for support of the current coordinated release
- [ ] Select **Repository** level **Project** for development toward the next official release or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next bugfix version

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>_main_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Organization** level software support **Project** for the current coordinated release
Select: **Milestone** as the next bugfix version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Close this issue.

**Comment by hsoh-u** [comment]
It's not simple to **use it's value instead of "obs_prepbufr_map" if "obs_prefbufr_map" is defined**.
The current way is 1) reading the default config and 2) reading the user config (overridding default connfig) . There is no way to figure if "obs_prefbufr_map" or "obs_prepbufr_map" are from the default config or from the user config. So "obs_prepbufr_map" is defined at the default config, the "obs_prefbufr_map" from the user config will be ignored.

So the reading order will be:
1. obs_prefbufr_map from a default config
2. obs_prefbufr_map from an user config (overrides the default config)
3. obs_prepbufr_map from a default config (overrides the user config)
4. obs_prepbufr_map from an user config (overrides the default config)

**Comment by JohnHalleyGotway** [comment]
@hsoh-u, I'm moving your email over to the GitHub issue comments section...

Cases to handle the bad key and some questions:

Two questions:

[default configuration]

If bad key (obs_prefbufr_map) exists at the default configuration:

- if good key (obs_prepbufr_map) does not exist, use it & give a warning
- Question 1: if good key (obs_prepbufr_map) exists, ignore it and give a warning OR no warning?

[user configuration]

If bad key exist at the user configuration, give a warning to correct key name
- if good key (obs_prepbufr_map) exist at default config.
  - Question 2: ignore or override to good key from default?
- if good key (obs_prepbufr_map) does not exist, override it from default

@hsoh-u there is NO distinction between "default configuration" and "user configuration", nor does there need to be. In pb2nc. This [line](https://github.com/dtcenter/MET/blob/221e14813aa77f099536c915f357abc9a325cf42/met/src/tools/other/pb2nc/pb2nc_conf_info.cc#L228) of pb2nc_conf_info.cc calls [parse_conf_obs_bufr_map()](https://github.com/dtcenter/MET/blob/9c45689439be6b1eaff6fd47b320cb5a511b05e6/met/src/basic/vx_config/config_util.cc#L1091). And this is the only code that actually needs to change (along with defining conf_key_obs_prepbufr_map)...

Existing:
```
map<ConcatString,ConcatString> parse_conf_obs_bufr_map(Dictionary *dict) {
   map<ConcatString,ConcatString> m = parse_conf_key_value_map(dict, conf_key_obs_prefbufr_map);
   parse_add_conf_key_value_map(dict, conf_key_obs_bufr_map, &m);
   return m;
}
```

New:
```
map<ConcatString,ConcatString> parse_conf_obs_bufr_map(Dictionary *dict) {
   map<ConcatString,ConcatString> m = parse_conf_key_value_map(dict, conf_key_obs_prefbufr_map, false);
   if(dict.last_lookup_status()) {
     // PRINT A WARNING MESSAGE HERE SINCE OBS_PREFBUFR_MAP IS PRESENT
   }
   else {
      m = parse_conf_key_value_map(dict, conf_key_obs_prepbufr_map, false);
   }
   parse_add_conf_key_value_map(dict, conf_key_obs_bufr_map, &m);
   return m;
}
```

Shoot, looks like I'm wrong. The "parse_add_conf_key_value_map()" does NOT have the optional "error_out" argument. Perhaps you'll need to add that as well. Otherwise, when you lookup "conf_key_obs_prefbufr_map", that lookup will fail and exit. We do not want to exit if its not present.

**Comment by hsoh-u** [comment]
I'm thinking not to change parse_conf_obs_bufr_map which is in the library code.
The warning will be given at pb2nc_conf_info.cc in order to print out which config file has a bad name. And correct the config key with the proper name.

The code will do following way:
```
PB2NCConfInfo::read_config

the current way:
   read a default config
   read an user config

new:
  read a default config
  check if warning case
  read an user config
  check if warning case
  if warning case, correct the config key & give warning
```
