### ISSUE TITLE
Fix inconsistent output when running HiRA

### ISSUE THREAD

**Issue by TaraJensen** [dtcenter/MET#2045]
## Describe the Problem ##
Rob and others at the Met Office were testing running HiRA using MET only and METplus.  They noticed that the output in the RPS line type was different between the two run configurations.  It boiled down to with MET only the TOTAL column was populated with realistic values.  The METplus run output TOTAL were all 0.  All other values in _rps.txt files were the same

Their debugging activity identified that:
MET only - ECNT and RPS output was turned on (they had it set to BOTH)
METplus - RPS was turned on, ECNT was not.

### Expected Behavior ###
The TOTAL column in RPS line type should be reported regardless of if ECNT output is requested. 

### Environment ###
Describe your runtime environment:
*1. Machine: (e.g. HPC name, Linux Workstation, Mac Laptop)*
*2. OS: (e.g. RedHat Linux, MacOS)*
*3. Software version number(s)*

### To Reproduce ###
Describe the steps to reproduce the behavior: - **working on defining this**
*1. I replicated the problem on seneca in /d1/personal/jensen/tutorial/METplus-4.0.0_Tutorial/output/met_output/point_stat
*2. PointStatConfig_tutorial_run2 has ECNT and RPS turned on
*3. PointStatConfig_tutorial_run3 only had RPS turned on
*4.  point_stat_run2_360000L_20070331_120000V_rps.txt - has valid data in the TOTAL column;
 point_stat_run3_360000L_20070331_120000V_rps.txt - has 0s

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
2702691

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Organization** level **Project** for support of the current coordinated release
- [ ] Select **Repository** level **Project** for development toward the next official release or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next bugfix version

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>_main_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Organization** level software support **Project** for the current coordinated release
Select: **Milestone** as the next bugfix version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
@TaraJensen thanks for setting up the nice test to illustrate the difference.

In seneca:/d1/personal/jensen/tutorial/METplus-4.0.0_Tutorial/output/met_output/point_stat and comparing those two files:
```
vimdiff point_stat_run[2,3]_360000L_20070331_120000V_rps.txt
```

I see that the differences are limited to the TOTAL column. Run 2 has the correct values and run 3 has all 0's. That tells me right where I should go look.

<img width="634" alt="Screen Shot 2022-02-11 at 2 18 30 PM" src="https://user-images.githubusercontent.com/21087144/153671586-a659d970-8b78-43b4-a159-b6326529fc2f.png">
