### ISSUE TITLE
Add support for reading National Blend Model GRIB2 data.

### ISSUE THREAD

**Issue by georgemccabe** [dtcenter/MET#2055]
This came up from GitHub Discussion dtcenter/METplus#1438

Reading NPM data results in the following error message:

> ERROR  : MetGrib2DataFile::data_plane() -> PDS template number (6) is not supported. Please email [met_help@ucar.edu](mailto:met_help@ucar.edu).

(Note: #2054 was created to address the email address in the error message)

Here's the PDS table:
https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_table4-0.shtml

Here's table 4.6:
https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/grib2_temp4-6.shtml

Here's where the new code is needed in MET:
https://github.com/dtcenter/MET/blob/5e1f551d86fcb5b731e3a83c0b043dbd7ef3c7aa/met/src/libcode/vx_data2d_grib2/data2d_grib2.cc#L692

## Describe the Enhancement ##
Add support for reading GRIB PDS template 6 data in the MET tools

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Recommend retrieving some National Blend Model data for testing:
[noaa-nbm-grib2-pds.s3.amazonaws.com/blend.20220215/13/core/blend.t13z.core.f119.co.grib2](https://noaa-nbm-grib2-pds.s3.amazonaws.com/blend.20220215/13/core/blend.t13z.core.f119.co.grib2)

Steps:
1. Update the GRIB2 library code to allow for this data type.
2. Run plot_data_plane with -v 4 to test that we can read it after retrieving a NBM file.
3. Compare log messages to wgrib2 output, specifically the timing info.
4. Add a new unit test that uses this sample data file.

**Comment by davidalbo** [comment]
Disclaimer:  I've never written any grib software and don't know much about the format.

I thought I'd compare table 4.5 to 4.6  to figure out what to do to add option 6, if anything.  The two tables are the same up to the last field in table 6, with additional fields in table 5.  Snippet of code shows ipdtnum 5 has this special action:

//  store the probability information, if appropriate
         if( 5 == gfld->ipdtnum || 9 == gfld->ipdtnum ){
            rec->ProbFlag  = true;
            rec->ProbType  = gfld->ipdtmpl[17];
            rec->ProbLower = (double)(gfld->ipdtmpl[19]) / pow( 10, (double)(gfld->ipdtmpl[18]) );
            rec->ProbUpper = (double)(gfld->ipdtmpl[21]) / pow( 10, (double)(gfld->ipdtmpl[20]) );
         } else {
            rec->ProbFlag  = false;
            rec->ProbType  = -1;
            rec->ProbLower = bad_data_double;
            rec->ProbUpper = bad_data_double;
         }


Table 5 does has a probability type in 'octet' 37, but the code here suggests it's in position 17.  I don't know what an octet is, so don't understand the array indexing between octets and the ipdtmp array shown here.

Anybody have a reference or easy explanation about how the code relates to the tables online?

**Comment by davidalbo** [comment]
What is the field name in the grib2 file  
[noaa-nbm-grib2-pds.s3.amazonaws.com/blend.20220215/13/core/blend.t13z.core.f119.co.grib2](https://noaa-nbm-grib2-pds.s3.amazonaws.com/blend.20220215/13/core/blend.t13z.core.f119.co.grib2)

  and how do you find out?

**Comment by JohnHalleyGotway** [comment]
Use "wgrib2" to inventory GRIB2 files:
```
$ wgrib2 ~/Downloads/blend.t13z.core.f119.co.grib2 
1:0:d=2022021513:APTMP:2 m above ground:119 hour fcst:
2:1471851:d=2022021513:CAPE:surface:119 hour fcst:
...
```

Each line of output summarizes one of the GRIB records in this file. I think there's 156 of them.

**Comment by davidalbo** [comment]
Sorry I'm a grib dummy.   The app plot_data_plane needs a field_string
I tried, for example:   CAPE,  CAPE:surface, CAPE:surface:119, 1471851... nothing seems to work:


Usage: plot_data_plane
	input_filename
	output_filename
	field_string
	[-color_table color_table_name]
	[-plot_range min max]
	[-title title_string]
	[-log file]
	[-v level]

	where	"input_filename" is the name of a gridded data file to be plotted (required).
		"output_filename" is the name of the output PostScript file to be written (required).
		"field_string" defines the data to be plotted from the input file (required).
		"-color_table color_table_name" overrides the default color table ("colortables/met_default.ctable") (optional).
		"-plot_range min max" defines the range of the data to be plotted (optional).
		"-title title_string" specifies the plot title string (optional).
		"-log file" outputs log messages to the specified file (optional).
		"-v level" overrides the default level of logging (4) (optional).

**Comment by JohnHalleyGotway** [comment]
@davidalbo please take a look at the plot_data_plane [online tutorial](https://dtcenter.org/metplus-practical-session-guide-version-4-0/session-1-metplus-setupgrid-grid/met-tool-plot-data-plane) instructions, and let me know if you have any questions.

This *should* work:
```
plot_data_plane blend.t13z.core.f119.co.grib2 CAPE.ps 'name="CAPE"; level="L0";'
```

... after you update the code to get around this error message:
```
ERROR  : 
ERROR  : MetGrib2DataFile::data_plane() -> PDS template number (6) is not supported. Please email met_help@ucar.edu.
ERROR  : 
```

**Comment by davidalbo** [comment]
Now I'm getting somewhere.  I can set up a before/after test.

seneca:/d1/personal/dave/MET/MET_development/MET/met/bin> ./plot_data_plane /d1/personal/dave/blend.t13z.core.f119.co.grib2 /d1/personal/dave/testout 'name="CAPE"; level="L0";'
DEBUG 1: Opening data file: /d1/personal/dave/blend.t13z.core.f119.co.grib2
ERROR  : 
ERROR  : MetGrib2DataFile::data_plane() -> PDS template number (6) is not supported. Please email met_help@ucar.edu.
ERROR  : 

Seems like the help message that you get by simply running the app with no arguments doesn't seem that useful as regards what you need to put on the command line as regards field_name.  The online tutorial documentation is very good.  I suppose it's way too much information to put into the code itself as a help message.  

Onward.

**Comment by davidalbo** [comment]
Adding option 6 leads to looking for option 10, which is also not supported.  Is this a 'whackamole' situation?  :-)

```
dave@seneca:/d1/personal/dave/MET/MET_development/MET/met/bin$ ./plot_data_plane /d1/personal/dave/blend.t13z.core.f119.co.grib2 /d1/personal/dave/testout 'name="CAPE"; level="L0";' -v 4
DEBUG 1: Opening data file: /d1/personal/dave/blend.t13z.core.f119.co.grib2
DEBUG 4: Met2dDataFileFactory::new_met_2d_data_file() -> created new Met2dDataFile object of type "FileType_Gb2".
DEBUG 4: 
DEBUG 4: Lambert Conformal Grid Data:
DEBUG 4:    hemisphere: N
DEBUG 4:   scale_lat_1: 25
DEBUG 4:   scale_lat_2: 25
DEBUG 4:       lat_pin: 19.229
DEBUG 4:       lon_pin: 126.277
DEBUG 4:         x_pin: 0
DEBUG 4:         y_pin: 0
DEBUG 4:    lon_orient: 95
DEBUG 4:          d_km: 2.5397
DEBUG 4:          r_km: 6371.2
DEBUG 4:            nx: 2345
DEBUG 4:            ny: 1597
DEBUG 4:     so2_angle: 0
DEBUG 4: 
DEBUG 4: MetGrib2DataFile::read_grib2_record_list() - unrecognized GRIB2 field indexes - disc: 0, master table: 1, center: 7, local table: 1, parm_cat: 19, parm: 239
DEBUG 4: MetGrib2DataFile::read_grib2_record_list() - unrecognized GRIB2 field indexes - disc: 0, master table: 1, center: 7, local table: 1, parm_cat: 19, parm: 239
DEBUG 4: MetGrib2DataFile::read_grib2_record_list() - unrecognized GRIB2 field indexes - disc: 0, master table: 1, center: 7, local table: 1, parm_cat: 19, parm: 239
DEBUG 4: MetGrib2DataFile::read_grib2_record_list() - unrecognized GRIB2 field indexes - disc: 0, master table: 1, center: 7, local table: 1, parm_cat: 19, parm: 239
DEBUG 4: MetGrib2DataFile::read_grib2_record_list() - unrecognized GRIB2 field indexes - disc: 0, master table: 1, center: 7, local table: 1, parm_cat: 19, parm: 239
DEBUG 4: MetGrib2DataFile::read_grib2_record_list() - unrecognized GRIB2 field indexes - disc: 0, master table: 1, center: 7, local table: 1, parm_cat: 19, parm: 239
DEBUG 4: MetGrib2DataFile::read_grib2_record_list() - unrecognized GRIB2 field indexes - disc: 0, master table: 1, center: 7, local table: 1, parm_cat: 19, parm: 239
DEBUG 4: MetGrib2DataFile::read_grib2_record_list() - unrecognized GRIB2 field indexes - disc: 0, master table: 1, center: 7, local table: 1, parm_cat: 19, parm: 239
DEBUG 4: MetGrib2DataFile::read_grib2_record_list() - unrecognized GRIB2 field indexes - disc: 0, master table: 1, center: 7, local table: 1, parm_cat: 19, parm: 239
DEBUG 4: MetGrib2DataFile::read_grib2_record_list() - unrecognized GRIB2 field indexes - disc: 0, master table: 1, center: 7, local table: 1, parm_cat: 19, parm: 239
DEBUG 4: MetGrib2DataFile::read_grib2_record_list() - unrecognized GRIB2 field indexes - disc: 0, master table: 1, center: 7, local table: 1, parm_cat: 19, parm: 239
DEBUG 4: MetGrib2DataFile::read_grib2_record_list() - unrecognized GRIB2 field indexes - disc: 0, master table: 1, center: 7, local table: 1, parm_cat: 19, parm: 239
DEBUG 4: MetGrib2DataFile::read_grib2_record_list() - unrecognized GRIB2 field indexes - disc: 0, master table: 1, center: 7, local table: 1, parm_cat: 19, parm: 239
DEBUG 4: MetGrib2DataFile::read_grib2_record_list() - unrecognized GRIB2 field indexes - disc: 0, master table: 1, center: 7, local table: 1, parm_cat: 19, parm: 238
DEBUG 4: MetGrib2DataFile::read_grib2_record_list() - unrecognized GRIB2 field indexes - disc: 0, master table: 1, center: 7, local table: 1, parm_cat: 1, parm: 228
DEBUG 4: MetGrib2DataFile::read_grib2_record_list() - unrecognized GRIB2 field indexes - disc: 10, master table: 1, center: 7, local table: 1, parm_cat: 3, parm: 204
ERROR  : 
ERROR  : MetGrib2DataFile::data_plane() -> PDS template number (10) is not supported. Please email met_help@ucar.edu.
ERROR  : 
```

**Comment by fortworthjack** [comment]
This is best place of reference I can recommend for details on NBM's GRIB2 files.  https://vlab.noaa.gov/web/mdl/nbm-grib-encoding

**Comment by JohnHalleyGotway** [comment]
@davidalbo, looking at this sample of GRIB2 records in an NBM model file, I see 2 issues (described below). Because of them, this will require more work than I initially guessed. I'd recommend reassigning this issue to MET version 11.0.0.

```
5:5227385:d=2022021513:CWASP:surface:119 hour fcst:5% level
25:19858985:d=2022021513:FICEAC:surface:95-119 hour acc@(fcst,dt=24 hour),missing=0:25% level
65:46397288:d=2022021513:WETBT:610 m above ground - 400 mb:119 hour fcst:spatial none:
```

1. Those variable names DO NOT appear in the existing MET GRIB2 tables: 
```
egrep -i "CWASP|FICEAC|WETBT" data/table_files/grib2_*
```
No results. So we'd need to update the GRIB2 tables defined in MET to get them in line with those defined in and used by wgrib2. Also cross-referencing the NBM documentation mentioned by @fortworthjack is a great idea. This is certainly doable, but non-trivial.

2. This whole "5% level" vs "25% level" is new to me. There is some GRIB2 table which defines those values, but I don't know what it is without looking. We'll need to add logic to the GRIB2 library code to check for this case, parse that field value and presumably add a configuration option to support filtering by that value. Lots of these filtering options already exist. For example, search for GRIB2_ens_type [here](https://met.readthedocs.io/en/develop/Users_Guide/config_options.html?highlight=grib2_ens_type).

I don't think we have enough time to add this and sufficiently test it in this development cycle.

**Comment by davidalbo** [comment]
Good to know that it's more than just the template numbers.  There may be other variable names that need the same attention.  These were just a few of the ones I chose to experiment with at random (that had the previously unsupported template numbers).

**Comment by sethlinden** [comment]
@davidalbo I am going to start working on this issue soon. I would like to run the last set of command lines you were running to test this (where you encountered the "PDS template number (10) is not supported").

Is the command line still: 

./plot_data_plane /d1/personal/dave/blend.t13z.core.f119.co.grib2 /d1/personal/dave/testout 'name="CAPE"; level="L0";' 

If so can you point me to the location of the input file the NBM file (blend.t13z.core.f119.co.grib2) or can you put it on /scratch somewhere so I can look at it.

Thanks in advance.

**Comment by sethlinden** [comment]
@davidalbo or @JohnHalleyGotway I just checked out a fresh copy of the development branch and ran plot_data_plane on the NBM input file...I'm still getting an error about "PDS template number (6) is not supported."

Looking a the comments above (from Feb 23rd), Dave got past this: "Adding option 6 leads to looking for option 10, which is also not supported. Is this a 'whackamole' situation?"

Where are these initial changes checked into GitHub? What file was "option 6" added to?

I'd like to get back to the point where it's complaining about "PDS template number (10) is not supported"?

Also, @JohnHalleyGotway what specific MET GRIB2 tables do we need to modify for NBM (so it recognizes the NBM fields)?

**Comment by davidalbo** [comment]
@sethlinden it's been a while!  I was playing around with this, and ended up never putting anything I experimented with into github.  I'd have to go back in to remember exactly what I'd done.  I'm assuming I built the system and ran it in the debugger, stopping at the place where option 6 is shown as an error, then made some kind of mod to deal with that.  The command line was indeed using /d1/personal/dave/blend.t13z.core.f119.co.grib2
That file is still there, can you get to it?

**Comment by sethlinden** [comment]
@davidalbo thanks for the info. I was able to grab NBM input file from your directory on seneca. Do you remember what file (module) you changed to get past the "(6) not supported" and got the "(10) not supported"? If not, I can search for it.

**Comment by davidalbo** [comment]
I don't remember, I figure you can figure it out as easily as I can go back in and re-remember,  but if you get stuck, I'll come back in and help out.

**Comment by sethlinden** [comment]
To make sure I have all the NBM fields defined, I interrogated several more example NBM data files at different lead-times. I used the following files for creating the new grib2_nbm.txt. I will also use these files for testing plot_data_plane.

The filles are currently located under: seneca:/d1/personal/linden/git/feature_2055_nbm_grib2_update/

blend.t12z.core.f001.co.grib2
blend.t12z.core.f003.co.grib2
blend.t12z.core.f006.co.grib2
blend.t12z.core.f012.co.grib2
blend.t12z.core.f019.co.grib2
blend.t12z.core.f024.co.grib2
blend.t13z.core.f119.co.grib2

**Comment by JohnHalleyGotway** [comment]
Seth, OK, this field string works to retrieve wet bulb temp: 'name="WETBT"; level="L610-40000";'
When levels are defined as being ranges, we specify them using the '-' syntax. This is mentioned in this section of the User's Guide.

The “level” entry specifies a level type and value:
ANNN for accumulation interval NNN
ZNNN for vertical level NNN
ZNNN-NNN for a range of vertical levels
PNNN for pressure level NNN in hPa
PNNN-NNN for a range of pressure levels in hPa
LNNN for a generic level type
RNNN for a specific GRIB record number

Some testing reveals that both "L610-40000" and "Z610-40000" work. This is definitely the first time I've seen a mixed level type! So perhaps we should add a new entry to this list for "LNNN-NNN"?

FYI, pressure levels are stored in GRIB headers as hectopascals. The MET library code translates that to millibars for user-convenience. However, in this case, MET is recognizing the mixed layer nature of this. It's just using first vertical level type... so the 40000 hpa isn't rescaled to 400 mb. So that's why we had to specify 40000 as the second level value.

I suppose we could add logic for better handling mixed layer types like this, but honestly, this may be a problem for another day. Maybe wait for the issue to come up a second time?
