### ISSUE TITLE
Fix OpenMP compilation error for GCC 9.3.0/9.4.0

### ISSUE THREAD

**Issue by j-opatz** [dtcenter/MET#2106]
## Describe the Problem ##
A user [Discussions](https://github.com/dtcenter/METplus/discussions/1529) alerted us to this issue. It appears that with the higher GCC versions, specifically 9.3.0 and 9.4.0, there is an error with shared OpenMP variables when `default(none)` is used. This was not seen in our development due to NCAR's systems running on GCC 8.3.0.

The linked Discussions will provide better detail on how to solve this issue.

### Expected Behavior ###
The compiler should call the .cc files and compile MET successfully. 

### Environment ###
Describe your runtime environment:
GCC > 9.0

### To Reproduce ###
Describe the steps to reproduce the behavior:
See Discussions post: it seems to be repeatable with a GCC > 9.0

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
2799991

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Organization** level **Project** for support of the current coordinated release
- [ ] Select **Repository** level **Project** for development toward the next official release or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next bugfix version

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>_main_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Organization** level software support **Project** for the current coordinated release
Select: **Milestone** as the next bugfix version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Close this issue.

**Comment by georgemccabe** [comment]
Here is the Docker image that contains GCC 9 and the external libraries dependencies:
dtcenter/met-base:unit_test_gcc9

Docker image we have been using that uses GCC 8:
dtcenter/met-base:unit_test

**Comment by JohnHalleyGotway** [comment]
Making progress testing the compilation of MET inside this Docker container for GCC9. The changes in bugfix_2106_main_v10.1_gcc get past the OpenMP compilation error but I'm getting this libz linker error when compiling plot_point_obs.

```
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: ../../../../src/libcode/vx_render/libvx_render.a(libvx_render_a-flate_filter.o): undefined reference to symbol 'deflate'
/opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld: /lib64/libz.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[4]: *** [plot_point_obs] Error 1
```

Need to debug that next.
