### ISSUE TITLE
Enhance plot_point_obs to filter observations based on the quality flag value in the obs_qty() variable.

### ISSUE THREAD

**Issue by davidfillmore** [dtcenter/MET#213]
Enhance plot_point_obs to filter observations based on the quality flag value in the obs_qty() variable.  Probably just add a new command line argument.
<i>[MET-213] created by johnhg</i>

**Comment by JohnHalleyGotway** [comment]
This request is handled by the plot_point_obs overhaul in #1528. The obs_qty strings can be filtered in the new plot_point_obs config file.

**Comment by JohnHalleyGotway** [comment]
Resolved by PR #1560
