### ISSUE TITLE
Add .zenodo.json file to add metadata about releases

### ISSUE THREAD

**Issue by jprestop** [dtcenter/MET#2198]
## Describe the Task ##
Add a [.zenodo.json file](https://developers.zenodo.org/#add-metadata-to-your-github-repository-release) to have zenodo automatically extract metadata about releases.

### Time Estimate ###
< 1 day

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
None

### Funding Source ###
Multiple keys provided by Tara in email to Julie

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
@jprestop, the current [MET Zenodo reference](https://zenodo.org/record/6705767) automatically generates an author list based on code contributions by username.

I'd recommend that we better define this in the json file either using...
1. The very long alphabetical [author list](https://met.readthedocs.io/en/latest/#authors) from the MET documentation.
2. The shorter [author list](https://met.readthedocs.io/en/latest/Users_Guide/index.html) from the citations section of the user's guide.

The second option is the list that we rotate for each official release. So if we use that, perhaps we also rotate the json list?

Another question... Should that "Citations" section be replaced by a link to the Zenodo page?

Recommend asking @TaraJensen for guidance.

**Comment by jprestop** [comment]
At the MET meeting today, we decided that we would use #1 minus the folks that aren't currently still working at NCAR/NOAA.  Also, I need to add Seth and Dave to the list in the documentation.
