### ISSUE TITLE
Bugfix: Fix the MET CF-Compliant NetCDF library code to Polar Stereographic data from NSIDC Sea Ice Edge NetCDF files.

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#2218]
## Describe the Problem ##
This issue arose via the dtcenter/METplus#1718 discussion. Further investigation reveals that the MET NetCDF-CF library code needs to be enhanced to instantiate Polar Stereographic grids from NSIDC Sea Ice Edge NetCDF files. Those file are CF-compliant but MET fails to read that data.

### Expected Behavior ###
MET should be able to read data from NSIDC Sea Ice Edge NetCDF file and instantiate the Polar Stereographic grids on which they resides.

### Environment ###
Describe your runtime environment:
*1. Machine: (e.g. HPC name, Linux Workstation, Mac Laptop)* Not Hardware-specific
*2. OS: (e.g. RedHat Linux, MacOS)* Not OS-specific
*3. Software version number(s)* version 10.1.0

### To Reproduce ###
Describe the steps to reproduce the behavior:
*1. Retrieve these sample data files:*
See [NSIDC_sample_data.tar.gz](https://github.com/dtcenter/MET/files/9244488/NSIDC_sample_data.tar.gz)
```
https://n5eil01u.ecs.nsidc.org/PM/NSIDC-0081.002/2022.07.23/NSIDC0081_SEAICE_PS_N25km_20220723_v2.0.nc
https://n5eil01u.ecs.nsidc.org/PM/NSIDC-0081.002/2022.07.23/NSIDC0081_SEAICE_PS_S25km_20220723_v2.0.nc
```
*2. Run plot_data_plane:*
```
plot_data_plane NSIDC0081_SEAICE_PS_S25km_20220723_v2.0.nc test.ps 'name="F16_ICECON"; level="(0,*,*)";' -v 4
```
*3. See error*
```
ERROR : get_nc_var_att_double() -> Cannot get "longitude_of_projection_origin" from crs variable.
```
*Post relevant sample data following these instructions:*
*https://dtcenter.org/community-code/model-evaluation-tools-met/met-help-desk#ftp*

The CF-Convention documentation defines Polar Stereographic grids [here](https://cfconventions.org/Data/cf-conventions/cf-conventions-1.9/cf-conventions.html#polar-stereographic). And this is parsed by the [get_grid_mapping_polar_stereographic()](https://github.com/dtcenter/MET/blob/0cbdd5f97437990e1ab4642d85de277a99242792/met/src/libcode/vx_data2d_nccf/nccf_file.cc#L2005) function in MET.

This task is to enhance MET's NCCF library to handle these files. 

Some initial testing got us closer but still produced an error:
```
ncatted \
-a longitude_of_projection_origin,crs,a,d,0 NSIDC0081_SEAICE_PS_N25km_20220723_v2.0.nc  \
-a scale_factor_at_projection_origin,crs,a,d,1.0 \
-a units,x,o,c,"m" \
-a units,y,o,c,"m" \
-o NSIDC0081_SEAICE_PS_N25km_20220723_v2.0_mod.nc
```
But the result still produces this error from MET:
```
ERROR  : NcCfFile::get_grid_mapping_polar_stereographic() -> MET can only process Polar Stereographic files where the x-axis and y-axis deltas are the same.
```

The X delta is +25000 m and the Y delta is -25000 m. So the magnitude is the same, but the sign is different.

If we ignore the sign, then MET is able to plot the result but the image is upside-down. So the library code need to detect this situation and flip the data accordingly, as is done in MET's GRIB1/2 libraries.

Please see the images in the attached tarfile to see how the data should actually be oriented.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
2773542 (was 2793541)

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Organization** level **Project** for support of the current coordinated release
- [x] Select **Repository** level **Project** for development toward the next official release or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next bugfix version

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdatadb](https://github.com/dtcenter/METdatadb/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts.

## Bugfix Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>_main_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Organization** level software support **Project** for the current coordinated release
Select: **Milestone** as the next bugfix version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
Per EMC, we need this bugfix in a 10.1.3 bugfix release ASAP.

**Comment by CPKalb** [comment]
This [discussion](https://github.com/dtcenter/METplus/discussions/1840) just came up.  It looks like this is a case where the standard parallel is specified as we discovered in the [first discussion](https://github.com/dtcenter/METplus/discussions/1718).   Will the fixes in this code take care of her issue as well?

**Comment by hsoh-u** [comment]
![radolan_polar_stereographics](https://user-images.githubusercontent.com/15203106/200101625-1da7ea66-baf0-457a-91a1-8022e7440396.png)

**Comment by hsoh-u** [comment]
MET does not support the polar stereographics for ellipsoidal Earth, yet.
The sample files above are for ellipsoidal Earth. It can be identified by 1) "inverse_flattening" attribute or 2) different values of semi_major_axis and semi_minor_axis attributes which are not required.

```
https://n5eil01u.ecs.nsidc.org/PM/NSIDC-0081.002/2022.07.23/NSIDC0081_SEAICE_PS_N25km_20220723_v2.0.nc
https://n5eil01u.ecs.nsidc.org/PM/NSIDC-0081.002/2022.07.23/NSIDC0081_SEAICE_PS_S25km_20220723_v2.0.nc

   crs:semi_major_axis = 6378273. ;
   crs:inverse_flattening = 298.279411123064 ;
OR
   crs:semi_major_axis = 6378273. ;
   crs:semi_minor_axis = 6356890.;
```
