### ISSUE TITLE
Add tmp_dir configuration option to the Plot-Point-Obs tool

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#2237]
## Describe the Enhancement ##
During development of a METplus wrapper for the Plot-Point-Obs tool, @georgemccabe noted two issues:
1. The Plot-Point-Obs config file currently lacks the tmp_dir configuration option. This is an oversight, and it should be added.
2. He also found that passing an empty configuration file to the MET tools results in a runtime error. This can be demonstrated using the `test_config` utility:
```
touch empty_file ; internal/test_util/basic/vx_config/test_config empty_file
...
ERROR  : yyerror() -> syntax error in file "/tmp/met_config_3387_0"
```

This task is to fix both issues. While 1. is a mandatory, the fix for 2. is only desired.

### Time Estimate ###
1 day

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
Non needed.

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
The METplus Plot-Point-Obs wrapper should be updated to handle setting tmp_dir.

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
So it is true that the Plot-Point-Obs config file DOES NOT contain entries for `tmp_dir` or `version`. Note however, that Plot-Point-Obs does first read ConfigConstants prior to reading it's default config file. And ConfigConstants DOES include the tmp_dir setting.

So `tmp_dir` actually is defined in this context since it was defined in ConfigConstants, but just not over-written in the default Plot-Point-Obs configuration file.

Technically then, `tmp_dir` could be removed from all of the other default config files. But doing so may cause confusion. Instead, I'll just add `tmp_dir` and `version` for Plot-Point-Obs.

**Comment by JohnHalleyGotway** [comment]
@georgemccabe I'm looking for some advice. I've made these changes for Plot-Point-Obs. Along the way, I also found that both `version` and `tmp_dir` are absent from [WWMCARegridConfig_default](https://github.com/dtcenter/MET/blob/develop/data/config/WWMCARegridConfig_default) and [PlotModeFieldConfig_default](https://github.com/dtcenter/MET/blob/develop/data/config/PlotModeFieldConfig_default). These are two lightly used MET tools for which no METplus wrapper exists.

For consistency reasons, should I add these options, update the code to parse them, test that they work, and update the documentation?

Or should I forgo the consistency and move onto to something that's higher priority, knowing that we'll want to do this if/when we add wrappers for them?

I lean toward the latter.

**Comment by georgemccabe** [comment]
I'd say it is up to you. It does seem low priority with little benefit besides consistency. On the other hand it would likely not take very much time to do. If you don't complete it now I would create a low priority GitHub issue so it is documented.

**Comment by JohnHalleyGotway** [comment]
OK, I chose not to include those changes here, but wrote it up as a separate issue #2243 to keep track of it.
