### ISSUE TITLE
Fix ascii2nc_airnow_hourly test in unit_ascii2nc.xml

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#2306]
## Describe the Problem ##
During review of #2294 for issue #2276, a problem was discovered in the output of the `ascii2nc_airnow_hourly` test in unit_ascii2nc.xml. The output file created by this test (HourlyData_20220312.nc) contains values of Infinity (`Inf`). While the GHA run for that PR did increase the occurrence of Inf in the output, the problem existed prior to those code changes.

This issue is to investigate the source of the `Inf` values appearing in the output, and fix the code to avoid them.

### Expected Behavior ###
The output of ascii2nc should never contain a value of infinity. The code should be enhanced by adding more error checking to avoid them. Perhaps, they should be reported as bad data value (i.e. -9999) rather than `Inf`?

Note that while Inf appears on seneca in 33 of 13738 lines, there are over 200 of them when run via GHA.

### Environment ###
Describe your runtime environment:
*1. Visible in the output of GHA and in the output of the MET nightly build on seneca.*

### To Reproduce ###
Describe the steps to reproduce the behavior:
*1. Log on to 'seneca'*
*2. Go to NB area:*
```
cd /d1/projects/MET/MET_regression/develop/NB20221018
```
*3. Dump to ascii:
```
Rscript MET-develop/scripts/Rscripts/pntnc2ascii.R MET-develop/test_output/ascii2nc/airnow/HourlyData_20220312.nc > HourlyData_20220312.txt
```
*4. See error in columns 6 and 9 of the output:*
```
 grep Inf HourlyData_20220312.txt  | wc -l
33
```
*Post relevant sample data following these instructions:*
*https://dtcenter.org/community-code/model-evaluation-tools-met/met-help-desk#ftp*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [x] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Organization** level **Project** for support of the current coordinated release
- [ ] Select **Repository** level **Project** for development toward the next official release or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next bugfix version

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>_main_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Organization** level software support **Project** for the current coordinated release
Select: **Milestone** as the next bugfix version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Close this issue.

**Comment by davidalbo** [comment]
This is tricky.  Will revisit tomorrow first thing.  Seems to (possibly) be something to do with the lookup file with latitude/longitudes.

**Comment by davidalbo** [comment]
@JohnHalleyGotway don't understand what I'm supposed to do here:
*Post relevant sample data following these instructions:*
*https://dtcenter.org/community-code/model-evaluation-tools-met/met-help-desk#ftp*

I believe I have a bug fix otherwise, and ready to do a pull request.
I was incorrectly setting an index into the lookup lat/lons when testing 3 different possible station id's (in the lookup file) against the station id found in the input ascii hourly file.
