### ISSUE TITLE
Fix ASCII2NC logic for reading AERONET v3 data

### ISSUE THREAD

**Issue by jprestop** [dtcenter/MET#2370]
## Describe the Problem ##
This issue arose with the METplus Discussion [dtcenter/METplus#1888](https://github.com/dtcenter/METplus/discussions/1888).  When the user obtained AERONET version 3 data from the [official site](https://aeronet.gsfc.nasa.gov) it was determined that the format was not consistent with the format of the data we currently use for our [unit testing](https://dtcenter.ucar.edu/dfiles/code/METplus/MET/MET_unit_test/unit_test/obs_data/aeronet/20150917_20150926_Table_Mountain.lev20).  Sample files from the new format and @hsoh-u's analysis of what would need to be done for this issue can be viewed within the Discussion at this [post](https://github.com/dtcenter/METplus/discussions/1888#discussioncomment-4319771).

### Expected Behavior ###
The MET code should be able to read AERONET v3 data obtained from the official site.

### Environment ###
Describe your runtime environment:
*1. Machine: not specific*
*2. OS: not specific*
*3. Software version number: all current releases*

### To Reproduce ###
Describe the steps to reproduce the behavior:
*1. Go to '...'*
*2. Click on '....'*
*3. Scroll down to '....'*
*4. See error*
*Post relevant sample data following these instructions:*
*https://dtcenter.org/community-code/model-evaluation-tools-met/met-help-desk#ftp*
Review the log file from Partha and read the data files he provided.

### Relevant Deadlines ###
MET-11.0.0 Official Release (12/7 - 12/9)

### Funding Source ###
2773542 

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Organization** level **Project** for support of the current coordinated release
- [x] Select **Repository** level **Project** for development toward the next official release or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next bugfix version

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>_main_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Linked issues**
Select: **Organization** level software support **Project** for the current coordinated release
Select: **Milestone** as the next bugfix version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
Select: **Reviewer(s)** and **Linked issues**
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
@hsoh-u please prioritize fixing this in the develop branch to be included in the MET version 11.0.0 release. Once it's fixed there, please port that fix over to the main_v10.1 branch. And we'll include it in any future MET-10.1 bugfix releases.
