### ISSUE TITLE
Bugfix: Fix ASCII2NC to not compute AOD 550 if other inputs are negative values

### ISSUE THREAD

**Issue by hsoh-u** [dtcenter/MET#2383]
*Replace italics below with details for this issue.*

## Describe the Problem ##
AOD 550nm is not computed when AOD 440 or AOD 675 is a missing value. The AERONET version 3 contains -999.0instead of "NA". It causes NaN as AOD at 550nm (because the argument for the log function should not be a negative number). So the AOD 550 should not be computed nor not saved to the output if AOD 440 or AOD 675 is a negative value

### Expected Behavior ###
The NaN is generated if -999.0 is accepted as a valid AOD value. This should be avoided.

### Environment ###
Describe your runtime environment:
*1. Machine: seneca*
*2. OS:(RedHat Linux)*
*3. Software version number(s): 11.0 & 10.1x*

### To Reproduce ###
Describe the steps to reproduce the behavior:
*1. Go to seneca*
*2. Download [AERONET V3 inpout text](https://github.com/dtcenter/METplus/files/10157774/20221202.lev15.txt)*
*3. Run command below*
*4. Check if it has NaN at the output*

```
./ascii2nc 20221202.lev15.txt aeronet_v3.output.nc
```
### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*
2773542

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Organization** level **Project** for support of the current coordinated release
- [ ] Select **Repository** level **Project** for development toward the next official release or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next bugfix version

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>_main_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Organization** level software support **Project** for the current coordinated release
Select: **Milestone** as the next bugfix version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
Select: **Reviewer(s)** and **Development** issue
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Close this issue.

**Comment by jprestop** [comment]
<h3>Release Acceptance Testing Summary</h3>

Version: MET-11.0.1-rc1
Date: 20230222
Location: Hera
Status (PASS/FAIL): PASS
Description: Please see my [comment](https://github.com/dtcenter/METplus/discussions/1888#discussioncomment-5080999) about testing this issue with Partha's code in the ["list of point data #1888" Discussion](https://github.com/dtcenter/METplus/discussions/1888).
