### ISSUE TITLE
Check the return status of the "make clean html" command in build_documentation.sh

### ISSUE THREAD

**Issue by jprestop** [dtcenter/MET#2436]
## Describe the Problem ##
Check the return status of the "make html" command in build_documentation.sh.  Currently, the GHA jobs still succeeds since we fail to return bad status from that script.
```
make clean html
if [ $? != 0 ]; then
  echo "ERROR: make clean html failed"
  exit 1
fi
cd -
```
See example [here](https://github.com/NCAR/wrfcloud/blob/develop/.github/jobs/build_documentation.sh).

Also consider adding the following:
```
  echo ERROR: Warnings/Errors found in documentation
  echo Summary:
  grep WARNING ${DOCS_DIR}/_build/warnings.log
  grep ERROR ${DOCS_DIR}/_build/warnings.log
  grep CRITICAL ${DOCS_DIR}/_build/warnings.log
  echo Review this log file or download documentation_warnings.log artifact
```
and
```
echo INFO: Documentation was built successfully.
```
See example [here](https://github.com/dtcenter/METplus/blob/main_v5.0/.github/jobs/build_documentation.sh).

### Expected Behavior ###
If "make clean html" returns a bad status, the GHA runs should also fail.

### Environment ###
Describe your runtime environment:
*1. Machine: (e.g. HPC name, Linux Workstation, Mac Laptop)*
*2. OS: (e.g. RedHat Linux, MacOS)*
*3. Software version number(s)*
**N/A**

### To Reproduce ###
Describe the steps to reproduce the behavior:
*1. Go to '...'*
*2. Click on '....'*
*3. Scroll down to '....'*
*4. See error*
*Post relevant sample data following these instructions:*
*https://dtcenter.org/community-code/model-evaluation-tools-met/met-help-desk#ftp*

### Relevant Deadlines ###
ASAP

### Funding Source ###
Split 2702691 and 2792542

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Projects and Milestone ###
- [x] Select **Organization** level **Project** for support of the current coordinated release
- [x] Select **Repository** level **Project** for development toward the next official release or add **alert: NEED PROJECT ASSIGNMENT** label
- [x] Select **Milestone** as the next bugfix version

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>_main_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Organization** level software support **Project** for the current coordinated release
Select: **Milestone** as the next bugfix version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
Select: **Reviewer(s)** and **Development** issue
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Close this issue.

**Comment by JohnHalleyGotway** [comment]
@jprestop, instead of returning bad status right away, we may want to stash the return status and include it in the conditional logic below.

```
make clean html
make_status = $?
cd -
...
if [ -s $warning_file || $make_status != 0 ]; then
```

But make sure you actually get the bash syntax correct.

**Comment by jprestop** [comment]
Closing as Not Planned although though this work will be accomplished with this overall [METplus issue: Enhancement: Enhance GHA documentation workflow with a custom action #2543](https://github.com/dtcenter/METplus/issues/2543). Closing this issue will remove it as duplicate issues in each repo and leave the issue in the METplus repo.
