### ISSUE TITLE
Update the documentation for the HSS and HSS_EC statistics

### ISSUE THREAD

**Issue by j-opatz** [dtcenter/MET#2492]
## Describe the Task ##
When the CPC project finished that formulated the HSS_EC creation, there was a suggested update to the documentation. That documentation was lost in the shuffle of finishing the project and getting use cases into the METplus repository, but is now being requested by CPC.

The documentation update is as follows:

> Suggestion would be to (a) Remove the CPC HSS equation from the HSS documentation, and (b) Place the CPC HSS equation in the MET documentation for HSS_EC (below) with (c) explaining that for the option of prescribing C2, it would be that C2 = T * E, where E is the expected number of correct forecasts and E = T * expected % hits. For example CPC typically expects the % of hits for a tercile category to hit 33 percent of the time. The expected % hits is set by the GRID_STAT_HSS_EC_VALUE as a value between 0 and 1. The Ou, 2016 reference can be included with explaining the usage of E (bounded 0 to 1). 

### Time Estimate ###
1-2 hours

### Sub-Issues ###
Consider breaking the task down into sub-issues.
- [ ] *Add a checkbox for each sub-issue here.*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Repository** and/or **Organization** level **Project(s)** or add **alert: NEED PROJECT ASSIGNMENT** label
- [ ] Select **Milestone** as the next official version or **Future Versions**

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Task Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issues
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by melissaOu** [comment]
CPC in house needs to work a little more on finalizing suggested documentation for HSS_EC. I will update comment here with a finalized version of suggested documentation edits when we are done.

**Comment by j-opatz** [comment]
The suggested updates to HSS and HSS_EC definitions were made to the develop branch and will appear in Appendix C
