### ISSUE TITLE
Bugfix: Fix the Grid-Stat configuration file to support the `MET_SEEPS_GRID_CLIMO_NAME` option 

### ISSUE THREAD

**Issue by mpm-meto** [dtcenter/MET#2601]
Trying to get SEEPS to work in grid_stat. There is nowhere to specify the location of the climatology, in either MET or METplus? 
Or where should it be set?

Also it refers to a name whereas the climatology is not a single file but by month. Both ascii and netcdf files exist. Not sure what to specify against this environment variable. 

It is also not clear whether the NC_PAIRS_FLAG (which exists in METplus) produces a 2D field of SEEPS scores and components but until we can run it we don't know. 

Refers: seeps.h 

## Describe the Problem ##
No SEEPS output produced. There may be a similar problem for the point_stat tool but not clear as yet.

### Expected Behavior ###
Create the SEEPS output. 

### Environment ###
RH Linux

### To Reproduce ###
Describe the steps to reproduce the behavior:
*1. Go to '...'*
*2. Click on '....'*
*3. Scroll down to '....'*
*4. See error*
*Post relevant sample data following these instructions:*
*https://dtcenter.org/community-code/model-evaluation-tools-met/met-help-desk#ftp*

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Projects and Milestone ###
- [ ] Select **Organization** level **Project** for support of the current coordinated release
- [ ] Select **Repository** level **Project** for development toward the next official release or add **alert: NEED CYCLE ASSIGNMENT** label
- [ ] Select **Milestone** as the next bugfix version

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>_main_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Organization** level software support **Project** for the current coordinated release
Select: **Milestone** as the next bugfix version
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
Select: **Reviewer(s)** and **Development** issue
Select: **Repository** level development cycle **Project** for the next official release
Select: **Milestone** as the next official version
- [ ] Close this issue.

**Comment by hsoh-u** [comment]
Option 1. set the environment variable MET_SEEPS_GRID_CLIMO_NAME
```
export MET_SEEPS_GRID_CLIMO_NAME=<path_for_SEEPS_climo>/<SEEPS_climo_name>
```
-- from User's Guide --
The SEEPS climo file is not distributed with MET tools because of the file size. It should be configured by using the environment variable, MET_SEEPS_GRID_CLIMO_NAME.

Option 2. Put "PPT24_seepsweights_grid.nc" to "$MET_BASE/climo/seeps" where **PPT24_seepsweights.nc** locates (SEEPS climo for point data).

The default setting (when the environment variable, MET_SEEPS_GRID_CLIMO_NAME is not set) is "$MET_BASE/climo/seeps/PPT24_seepsweights_grid.nc".

I uploaded PPT24_seepsweights_grid.nc to ftp.rap.ucar.edu:/incoming/irap/met_help/howard_seeps.

**Comment by mpm-meto** [comment]
Where are we in terms of resolving this for all users? Am I right in recalling that we were going to push that netcdf file to something like zenodo and adding the link to the documentation?

**Comment by JohnHalleyGotway** [comment]
@mpm-meto yes I recall that discussion as well. But to my knowledge that has not yet occurred. Is this something that the METplus team should do? Or should we expect @RachelNorth to do this? Regardless, we will need to update the MET User's Guide to point to the location of this dataset.

**Comment by jprestop** [comment]
@hsoh-u Can you please provide a status update and let me know if any more work is needed on this before the 12.0.0-beta5 release?  Or should this be moved to beta6?

**Comment by hsoh-u** [comment]
I will create a PR today (working on the documentation)
