### ISSUE TITLE
Fix the SonarQube findings for MET version 12.0.0

### ISSUE THREAD

**Issue by hsoh-u** [dtcenter/MET#2673]
Nightly scanning reports the SonarQube finds. They should be resolved with MET v12.0 release.

Note that work on this issue will occur during each development cycle toward the MET-12.0.0 release.

## Describe the Enhancement ##
The newly introduced [SonarQube findings](http://needham.rap.ucar.edu:9000/dashboard?id=MET_develop_NB) should be resolved with v12.0 release. And reduce the code smell as possible.

SonarQube: All rules [for C](https://rules.sonarsource.com/c/) and [for CPP](https://rules.sonarsource.com/cpp/)
- `using namespace` statements
  - [after `#include` directives](https://rules.sonarsource.com/cpp/type/Code%20Smell/RSPEC-954/)
  - [not in the header files](https://rules.sonarsource.com/cpp/type/Code%20Smell/RSPEC-1003/)
- [remove redundant parentheses](https://rules.sonarsource.com/c/RSPEC-1110/) 
   - with return statement `return ( true );` --\> `return true;`
   - Note: `return ( digit_count > 0 );` is not considered as redundant parentheses
- [use `nullptr` instead of the literal 0 as pointer](https://rules.sonarsource.com/cpp/type/Code%20Smell/M23_064/)
- [reduce the scope of the local variables](https://rules.sonarsource.com/cpp/type/Code%20Smell/RSPEC-6004/)
  - local variable into loop statement [`for (int i=0;i<i_end; i++)` instead of `int i; for (i=0; i<i_end;i++)`](https://rules.sonarsource.com/c/RSPEC-5955/)
- [`enum` to `enum class`](https://rules.sonarsource.com/cpp/type/Code%20Smell/RSPEC-6177/)  #2830
- [`while (true)` instead of `while{1)`](https://rules.sonarsource.com/cpp/type/Code%20Smell/RSPEC-5820/)
- [Assignments should not be made from within conditions](https://rules.sonarsource.com/c/RSPEC-1121/) `if (x = getValue())` to `x = getValue(); if (x)`
- [Extract the assignment the this expression: need login](https://needham.rap.ucar.edu/coding_rules?open=cpp%3AS1121&rule_key=cpp%3AS1121): mostly `++i` or `i++`as an argument. For example, `k++` at `table.set_entry(r, k++, (string)"N");`
- Replace dynamically allocated memory with STL vectors, where possible. Replace `new <data_type>` statements with `vector<data_type>` and call the `vector::data()` member function to get a pointer to that memory (e.g. when calling NetCDF library to read data from input files into memory).

### Time Estimate ###
*Estimate the amount of work required here.*
*Issues should represent approximately 1 to 3 days of work.*

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
None needed.

### Relevant Deadlines ###
SonarQube findings should be minimized during each development cycle toward the MET-12.0.0 release.

### Funding Source ###
Prior to FY25 - 2771022 AIR FORCE METPLUS
FY25 - 2771024 Air Force METplus

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Review default **alert** labels
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Milestone and Projects ###
- [x] Select **Milestone** as the next official version or **Backlog of Development Ideas**
- [x] For the next official version, select the **MET-X.Y.Z Development** project

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts.

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the next official version
Select: **MET-X.Y.Z Development** project for development toward the next official release
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by jprestop** [comment]
@hsoh-u Can you please provide a status update and let me know if any more work is needed on this before the 12.0.0-beta5 release?

**Comment by hsoh-u** [comment]
I moved this to beta 6. This is ongoing between cycles.

**Comment by JohnHalleyGotway** [comment]
@hsoh-u I'm going to close this SonarQube issue for MET-12.0.0 since PR #2999 did in fact remove the last bug in `wchar_argv.cc`. Also, we've hit our limit of 10+ PR's linking to this same issue!

I do not think any additional concerted SonarQube efforts are required for the MET-12.0.0, but of course, we can continue driving down the code smells with each PR we submit. If more targeted SonarQube work is identified, let's just create a new issue to track that work.

Thanks for all of your hard work on those 10+ PR's!
