### ISSUE TITLE
Bugfix: Investigate unexpected number of derived HPBL observations in PB2NC

### ISSUE THREAD

**Issue by jprestop** [dtcenter/MET#2687]
## Describe the Problem ##
When committing ONLY a filename change directly in the develop branch, the [GitHub Actions run](https://github.com/dtcenter/MET/actions/runs/6240000815) produced a failure at the "Check for Differences" step.  Asking about it on GitHub, @JohnHalleyGotway indicated that these derived PBL obs also recently caused diffs when we switched METbaseimage to Debian 12:
https://github.com/dtcenter/MET/actions/runs/6101796818/job/16560081693?pr=2675
The PBL derivation doesn't seem to be as repeatable as it should be.  We need to look into the details of [calpbl.f](https://github.com/dtcenter/MET/blob/develop/src/tools/other/pb2nc/calpbl.f) to debug and tighten up the logic.
@georgemccabe noted that this issue is the likely cause of the use case diffs as described in [Enhancement: Improve PBL use case to generate reproducible results #2246](https://github.com/dtcenter/METplus/issues/2246).  

### Expected Behavior ###
The 9 missing derived HPBL obs should not be missing.
```
python MET-develop/scripts/python/utility/print_pointnc2ascii.py nam.20210311.t00z.prepbufr.tm00.pbl_TRUTH.nc > nam.20210311.t00z.prepbufr.tm00.pbl_TRUTH.txt

python MET-develop/scripts/python/utility/print_pointnc2ascii.py nam.20210311.t00z.prepbufr.tm00.pbl_OUTPUT.nc > nam.20210311.t00z.prepbufr.tm00.pbl_OUTPUT.txt

diff nam.20210311.t00z.prepbufr.tm00.pbl_TRUTH.txt nam.20210311.t00z.prepbufr.tm00.pbl_OUTPUT.txt
```
Here are the differences:
```
99d98
< ADPUPA 70398   20210311_000000 55.05 -131.5900   35 HPBL   NA 0 9  103.87126160
102d100
< ADPUPA 70326   20210311_000000 58.68 -156.6700    8 HPBL   NA 0 9  130.87126160
108d105
< ADPUPA 70273   20210311_000000 61.16 -149.9900   52 HPBL   NA 0 9   86.87126160
117d113
< ADPUPA 71957   20210311_000000 68.32 -133.5300  103 HPBL   NA 0 9   35.87126160
132d127
< ADPUPA 76903   20210311_000000 14.88  -92.3000  119 HPBL   NA 0 9   19.87126160
145d139
< ADPUPA 72240   20210311_000000 30.13  -93.2200    5 HPBL   NA 0 9  133.87126160
377d370
< ADPUPA 70261   20210311_000000 64.82 -147.8800  134 HPBL   NA 0 9    4.87126160
383d375
< ADPUPA 71917   20210311_000000 80.00  -85.9300   10 HPBL   NA 0 9  128.87126160
386d377
< ADPUPA 71082   20210311_000000 82.50  -62.3500   76 HPBL   NA 0 9   62.87126160
```
### Environment ###
Describe your runtime environment:
GitHub Actions

### To Reproduce ###
Describe the steps to reproduce the behavior:
*1. Go to '...'*
*2. Click on '....'*
*3. Scroll down to '....'*
*4. See error*
*Post relevant sample data following these instructions:*
*https://dtcenter.org/community-code/model-evaluation-tools-met/met-help-desk#ftp*

### Relevant Deadlines ###
Beta2

### Funding Source ###
2792543 - NOAA Base

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Review default **alert** labels
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Milestone and Projects ###
- [x] Select **Milestone** as the next bugfix version
- [x] Select **Coordinated METplus-X.Y Support** project for support of the current coordinated release
- [x] Select **MET-X.Y.Z Development** project for development toward the next official release

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>_main_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the next bugfix version
Select: **Coordinated METplus-X.Y Support** project for support of the current coordinated release
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the next official version
Select: **MET-X.Y.Z Development** project for development toward the next official release
- [ ] Close this issue.

**Comment by hsoh-u** [comment]
Where can I get  the "nam.20210311.t00z.prepbufr.tm00.pbl_TRUTH.nc"?

**Comment by jprestop** [comment]
Great question @hsoh-u.  I did a quick check on seneca and see nothing:

> seneca:jpresto:/d1/projects/MET> locate  nam.20210311.t00z.prepbufr.tm00.pbl_TRUTH.nc
seneca:jpresto:/d1/projects/MET> 

@JohnHalleyGotway Where can @hsoh-u access this file?

**Comment by georgemccabe** [comment]
It should be in the diff artifact from the GHA run that flagged differences.

**Comment by hsoh-u** [comment]
The matching log for the first missing one `ADPUPA 70398   20210311_000000 55.05 -131.5900   35 HPBL   NA 0 9  103.87126160`. The PBL value is different and filtered out.
- 2 records for the TQZ (at 101700mb and 1000mb)
- 36 records for UV (two records were discarded during merging: pressure = 930mb and 860mb)
- Common pressure: 1 (pressure 1000mb)
- 35 merged records (35 = 2 + 34 - 1) 
```
DEBUG 8: compute_pbl() input to calpbl_ (buffer): index, P, Q, T, Z, U, V
DEBUG 8: compute_pbl()   0       -136673597379257383059938344960.00000 0.00000 -106153509484448810401246740480.00000 0.00000 13.90000 3.70000
DEBUG 8: compute_pbl()   1       1010.00006 0.00002 216.38368 30480.00000 6.10000 -2.80000
DEBUG 8: compute_pbl()   2       1110.00000 0.00008 217.65215 29870.00000 14.30000 1.30000
DEBUG 8: compute_pbl()   3       1220.00000 0.00013 218.92169 29261.00000 0.20000 2.60000
DEBUG 8: compute_pbl()   4       1280.00000 0.00016 219.56673 28956.00000 6.20000 0.00000
DEBUG 8: compute_pbl()   5       1350.00000 0.00019 220.28210 28639.00000 7.70000 0.70000
DEBUG 8: compute_pbl()   6       1629.99988 0.00029 222.81439 27432.00000 3.30000 3.90000
DEBUG 8: compute_pbl()   7       1710.00000 0.00032 223.45815 27127.00000 0.90000 5.00000
DEBUG 8: compute_pbl()   8       1979.99988 0.00040 225.42786 26213.00000 3.70000 8.00000
DEBUG 8: compute_pbl()   9       2080.00000 0.00043 226.08984 25908.00000 1.90000 6.90000
DEBUG 8: compute_pbl()   10      2190.00000 0.00046 226.78223 25603.00000 -0.90000 5.00000
DEBUG 8: compute_pbl()   11      2410.00000 0.00051 228.06837 24994.00000 2.90000 4.20000
DEBUG 8: compute_pbl()   12      2530.00000 0.00054 228.72124 24689.00000 0.00000 0.00000
DEBUG 8: compute_pbl()   13      2660.00000 0.00057 229.39445 24384.00000 0.60000 -1.40000
DEBUG 8: compute_pbl()   14      2790.00000 0.00060 230.03555 24079.00000 5.10000 0.40000
DEBUG 8: compute_pbl()   15      2920.00000 0.00062 230.64745 23774.00000 3.30000 7.00000
DEBUG 8: compute_pbl()   16      3070.00000 0.00065 231.32050 23470.00000 -2.60000 5.60000
DEBUG 8: compute_pbl()   17      3220.00000 0.00068 231.96143 23165.00000 -4.40000 -2.50000
DEBUG 8: compute_pbl()   18      3380.00000 0.00070 232.61298 22860.00000 -0.90000 -2.40000
DEBUG 8: compute_pbl()   19      3909.99976 0.00079 234.57004 21946.00000 3.60000 -3.60000
DEBUG 8: compute_pbl()   20      4310.00000 0.00084 235.87868 21336.00000 7.10000 -4.10000
DEBUG 8: compute_pbl()   21      4520.00000 0.00087 236.51787 21031.00000 5.50000 -4.60000
DEBUG 8: compute_pbl()   22      4980.00000 0.00092 237.82002 20422.00000 4.80000 1.70000
DEBUG 8: compute_pbl()   23      5230.00000 0.00095 238.47812 20117.00000 3.90000 -3.30000
DEBUG 8: compute_pbl()   24      5490.00000 0.00098 239.12997 19812.00000 6.20000 -0.50000
DEBUG 8: compute_pbl()   25      5760.00000 0.00100 239.77501 19507.00000 5.00000 0.90000
DEBUG 8: compute_pbl()   26      6650.00000 0.00108 241.70543 18593.00000 1.30000 -4.90000
DEBUG 8: compute_pbl()   27      6969.99951 0.00111 242.33688 18288.00000 2.90000 -4.20000
DEBUG 8: compute_pbl()   28      7319.99951 0.00114 242.99518 17983.00000 0.00000 -5.70000
DEBUG 8: compute_pbl()   29      7669.99951 0.00116 243.62271 17678.00000 5.70000 -9.80000
DEBUG 8: compute_pbl()   30      8050.00000 0.00119 244.27238 17374.00000 6.70000 -4.70000
DEBUG 8: compute_pbl()   31      8440.00000 0.00122 244.90804 17069.00000 6.20000 -3.60000
DEBUG 8: compute_pbl()   32      8850.00000 0.00125 245.54536 16764.00000 3.90000 -8.40000
DEBUG 8: compute_pbl()   33      98370.00000 0.00260 277.90271 305.00000 4.00000 0.70000
DEBUG 8: compute_pbl()   34      101700.00000 0.00262 278.35001 35.00000 -9999.00000 -9999.00000
DEBUG 4: Not saved because the computed PBL (3.078372466e-41) is less than the station elevation (35). 20210311_000000 ADPUPA 70398
```

The pressure of the first PBL input record is not correct (should 1000). It's corrected, but still filtered out
```
DEBUG 7: compute_pbl() pbl_level= 35 from TQ (2) and UV (36)
DEBUG 8:
DEBUG 8: compute_pbl() input to calpbl_ (buffer): index, P, Q, T, Z, U, V
DEBUG 8: compute_pbl()   0       1000.00000 0.00002 216.25000 31496.00000 13.90000 3.70000
DEBUG 8: compute_pbl()   1       1010.00006 0.00002 216.38368 30480.00000 6.10000 -2.80000
DEBUG 8: compute_pbl()   2       1110.00000 0.00008 217.65215 29870.00000 14.30000 1.30000
...
DEBUG 7:  hpbl: 31496, obs_arr[4]: 31461   lat: 55.04999924, lon: -131.5899963, elv: 35 20210311_000000 ADPUPA 70398
DEBUG 7:
DEBUG 4: Not saved the computed PBL (31461 from 31496) because of the MAX PBL 10000  (20210311_000000 ADPUPA 70398)
```

**Comment by hsoh-u** [comment]
9 PBL values were  filtered out with the nightly build:
```
/d1/projects/MET/MET_regression/develop/NB20230929/MET-develop/bin/pb2nc /d1/personal/hsoh/data/MET-1715/nam.20210311.t00z.prepbufr.tm00 nam.20210311.t00z.prepbufr.tm00.pbl.nc /d1/personal/hsoh/data/MET-1715/PB2NCConfig_case_6_10 -v 4 | grep " Not saved because the computed PBL"  | egrep  "70398|70326|70273|71957|76903|72240|70261|71917|71082"
DEBUG 4: Not saved because the computed PBL (3.07627e-41) is less than the station elevation (35). 20210311_000000 ADPUPA 70398
DEBUG 4: Not saved because the computed PBL (3.07627e-41) is less than the station elevation (8). 20210311_000000 ADPUPA 70326
DEBUG 4: Not saved because the computed PBL (3.07627e-41) is less than the station elevation (52). 20210311_000000 ADPUPA 70273
DEBUG 4: Not saved because the computed PBL (3.07627e-41) is less than the station elevation (103). 20210311_000000 ADPUPA 71957
DEBUG 4: Not saved because the computed PBL (3.07627e-41) is less than the station elevation (119). 20210311_000000 ADPUPA 76903
DEBUG 4: Not saved because the computed PBL (3.07627e-41) is less than the station elevation (5). 20210311_000000 ADPUPA 72240
DEBUG 4: Not saved because the computed PBL (3.07627e-41) is less than the station elevation (134). 20210311_000000 ADPUPA 70261
DEBUG 4: Not saved because the computed PBL (3.07627e-41) is less than the station elevation (10). 20210311_000000 ADPUPA 71917
DEBUG 4: Not saved because the computed PBL (3.07627e-41) is less than the station elevation (76). 20210311_000000 ADPUPA 71082
```

**Comment by JohnHalleyGotway** [comment]
@hsoh-u and @JohnHalleyGotway met on Oct 10, 2023 and decided to rerun the full set of unit tests for `develop-ref` with this [GHA run](https://github.com/dtcenter/MET/actions/runs/6474492922). Check the number of obs in `nam.20210311.t00z.prepbufr.tm00.pbl.nc`. If it's still 401, then there is more debugging to be done. If it's 392 (which we've been getting since), then let's just update `develop-ref` to move past this difference.

I note that we did run the following commands:
```
docker run -it --rm -v /Volumes/d1/projects/MET/MET_unit_test/MET_test_input:/data dtcenter/met-dev:develop-ref /bin/bash
pb2nc /data/obs_data/prepbufr/nam.20210311.t00z.prepbufr.tm00 nam.20210311.t00z.prepbufr.tm00.pbl.test.nc MET-develop-ref/internal/test_unit/config/PB2NCConfig_pbl -log run_pb2nc.log -v 8
```
And the PB2NC output file there contained 392 (not 401).

**UPDATE** That GHA run produced 392 obs, not 401. So this issue cannot reasonably be replicated:
```
COMPARING pb2nc_indy/nam.20210311.t00z.prepbufr.tm00.pbl.nc
file1: /data/output/met_test_truth/pb2nc_indy/nam.20210311.t00z.prepbufr.tm00.pbl.nc
file2: /data/output/met_test_output/pb2nc_indy/nam.20210311.t00z.prepbufr.tm00.pbl.nc
ERROR: NetCDF headers differ:
7c7
< 	nobs = 401 ;
---
> 	nobs = 392 ;
```
Recommend just updating `develop-ref` to move past this difference, subject to any other changes that Howard would like to make.

**Comment by hsoh-u** [comment]
[The github action against develop-ref](https://github.com/dtcenter/MET/actions/runs/6474492922/job/17580636349) has the same difference.
```
 /usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +80afcac6e3906ac84b38ee678df640968c47b059:refs/remotes/origin/develop-ref

COMPARING pb2nc_indy/nam.20210311.t00z.prepbufr.tm00.pbl.nc
file1: /data/output/met_test_truth/pb2nc_indy/nam.20210311.t00z.prepbufr.tm00.pbl.nc
file2: /data/output/met_test_output/pb2nc_indy/nam.20210311.t00z.prepbufr.tm00.pbl.nc
ERROR: NetCDF headers differ:
7c7
< 	nobs = 401 ;
---
> 	nobs = 392 ;
```

**Comment by hsoh-u** [comment]
The PBL input for Fortran code is initialized [here](https://github.com/dtcenter/MET/blob/develop/src/tools/other/pb2nc/pb2nc.cc#L3173-L3181)
