### ISSUE TITLE
Add export for MAKE_ARGS

### ISSUE THREAD

**Issue by HathewayWill** [dtcenter/MET#2715]
Change This in the compile_MET_all.sh

TEST_BASE = /home/workhorse/WRF_SFIRE/MET-11.1.0
COMPILER  = intel_2021.10.0
MET_SUBDIR = /home/workhorse/WRF_SFIRE/MET-11.1.0
MET_TARBALL = v11.1.0.tar.gz
USE_MODULES = FALSE

to 

TEST_BASE = /home/workhorse/WRF_SFIRE/MET-11.1.0
COMPILER  = intel_2021.10.0
MET_SUBDIR = /home/workhorse/WRF_SFIRE/MET-11.1.0
MET_TARBALL = v11.1.0.tar.gz
USE_MODULES = FALSE
MAKE_ARGS=-j   (If present)

## Describe the Enhancement ##
Adding an export string to the shell script that shows the MAKE_ARGS is enabled when -j or anything else is exported

**Comment by jprestop** [comment]
Hi @HathewayWill.  You requested "Adding an export string to the shell script that shows the MAKE_ARGS is enabled when -j or anything else is exported", but from the context of the description it looks like perhaps you want an echo statement (as opposed to an export statement) to print out the value of MAKE_ARGS if one exists.  Is that correct?  If so, please note that this already exists in our develop branch at [this line](https://github.com/dtcenter/MET/blob/9a71af548542da3352d831b303db5a9edd2b340e/internal/scripts/installation/compile_MET_all.sh#L109) and will be contained in our next release.

**Comment by HathewayWill** [comment]
That's what I wanted.  You're one step ahead of me

**Comment by jprestop** [comment]
@HathewayWill, great!  Thanks for confirming. Since this work is already completed, I will close this issue with this comment.
