### ISSUE TITLE
Bugfix: Fix Python embedding failure when providing a single point observation

### ISSUE THREAD

**Issue by DanielAdriaansen** [dtcenter/MET#2755]
## Describe the Problem ##
I was using `point2grid` for another project and was doing some double checking of my data. I discovered that when I created the MET 11-column object for Python embedding for point data, but it only had one observation (one line) in the object, Python embedding fails:
```
DEBUG 3: Initializing MET compile time python instance: /usr/local/met-python3.10/bin/python3
DEBUG 3: Running MET compile time python instance (/usr/local/met-python3.10/bin/python3) to run user's python script (read_one_line).
[['NA', 'NA', '20231204_000000', 44.03, -72.57, -9999.0, 'TEST_VAR', -9999.0, -9999.0, 'NA', 1.0]]
ERROR  : 
ERROR  : process_point_data_list -> The header is empty. Please check the python script and input
ERROR  : 
```

Interestingly, if I copy that line and create a file with 10 observations, but every line is the same, it also fails. If I change even one character on one of the lines with 10 observations, it succeeds.

### Expected Behavior ###
At a minimum, if there is only 1 observation in the object passed, the MET tools should succeed. I'm not sure what we want the behavior to be if the user passes 100 observations that are identical.

### Environment ###
Seneca

### To Reproduce ###
On seneca, there is a directory demonstrating various combinations:
/home/dadriaan/projects/pythonpointoneline

### Relevant Deadlines ###
*List relevant project deadlines here or state NONE.*

### Funding Source ###
*Define the source of funding and account keys here or state NONE.*
2702691

### Assignee ###
- [ ] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [ ] Review default **alert** labels
- [ ] Select **component(s)**
- [ ] Select **priority**
- [ ] Select **requestor(s)**

### Milestone and Projects ###
- [ ] Select **Milestone** as the next bugfix version
- [ ] Select **Coordinated METplus-X.Y Support** project for support of the current coordinated release
- [ ] Select **MET-X.Y.Z Development** project for development toward the next official release

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [ ] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)

## Bugfix Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **main_\<Version>**.
Branch name: `bugfix_<Issue Number>_main_<Version>_<Description>`
- [ ] Fix the bug and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **main_\<Version>**.
Pull request: `bugfix <Issue Number> main_<Version> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the next bugfix version
Select: **Coordinated METplus-X.Y Support** project for support of the current coordinated release
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Complete the steps above to fix the bug on the **develop** branch.
Branch name:  `bugfix_<Issue Number>_develop_<Description>`
Pull request: `bugfix <Issue Number> develop <Description>`
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the next official version
Select: **MET-X.Y.Z Development** project for development toward the next official release
- [ ] Close this issue.

**Comment by DanielAdriaansen** [comment]
This may be related: https://github.com/dtcenter/MET/pull/2529

**Comment by DanielAdriaansen** [comment]
For now for my purposes, I have inserted a second observation and forced the lat/lon to a location off the grid to bypass the problem.

**Comment by hsoh-u** [comment]
The python script name seems to be "read_one_line.py". Where is it?
It would be nice to have the command to reproduce the problem.
```
DEBUG 3: Running MET compile time python instance (/usr/local/met-python3.10/bin/python3) to run user's python script (read_one_line).
```

**Comment by DanielAdriaansen** [comment]
Hi @hsoh-u. In the issue description under "To Reproduce" I note:

> On seneca, there is a directory demonstrating various combinations:
/home/dadriaan/projects/pythonpointoneline

Let me know if you can't read that area.
