### ISSUE TITLE
Improve MET library logging for NetCDF level dimension matches

### ISSUE THREAD

**Issue by JohnHalleyGotway** [dtcenter/MET#3038]
## Describe the Enhancement ##
Improve logging for NetCDF level dimension matches. @DanielAdriaansen had questions about how the level string he provided to `plot_data_plane` was being used to read data from the input NetCDF file.

For example, using the sample data in seneca ` /home/dadriaan/projects/NRL/CSU_Satellite/GEO-stitch-cloud3d_L3_2.3.1_20241108T1800Z_CONUS.nc`, run the following 2 commands:
```
plot_data_plane GEO-stitch-cloud3d_L3_2.3.1_20241108T1800Z_CONUS.nc obs.ps 'name="cloud3d"; level="(@0.5,*,*)"; file_type=NETCDF_NCCF;' -v 7

plot_data_plane GEO-stitch-cloud3d_L3_2.3.1_20241108T1800Z_CONUS.nc obs.ps 'name="cloud3d"; level="(0.5,*,*)"; file_type=NETCDF_NCCF;'
```

For the first, no log message states how `@0.5` was actually converted into a dimension index.
And for the second, no warning message points out that `0.5` is passed through `atoi(0.5)` and converted into index = 0.

Fix the first by adding the following log message:
```
DEBUG 7: MetNcCFDataFile::convert_value_to_offset() -> Found "altitude" dimension value of "0.5" at dimension index 1.
```
And fix the second with a warning message:
```
WARNING: 
WARNING: check_dim_offset() -> Found non-integer NetCDF dimension index (0.5 != 0).
WARNING: Did you intend to use "@0.5" to specify the value for that dimension instead?
WARNING: 
``` 

### Time Estimate ###
4 hours.

### Sub-Issues ###
Consider breaking the enhancement down into sub-issues.
None

### Relevant Deadlines ###
None

### Funding Source ###
Use NRL METplus 7730022 since it came up during that testing

### Assignee ###
- [x] Select **engineer(s)** or **no engineer** required
- [ ] Select **scientist(s)** or **no scientist** required

### Labels ###
- [x] Review default **alert** labels
- [x] Select **component(s)**
- [x] Select **priority**
- [x] Select **requestor(s)**

### Milestone and Projects ###
- [x] Select **Milestone** as a **MET-X.Y.Z** version, **Consider for Next Release**, or **Backlog of Development Ideas**
- [x] For a **MET-X.Y.Z** version, select the **MET-X.Y.Z Development** project

## Define Related Issue(s) ##
Consider the impact to the other METplus components.
- [x] [METplus](https://github.com/dtcenter/METplus/issues/new/choose), [MET](https://github.com/dtcenter/MET/issues/new/choose), [METdataio](https://github.com/dtcenter/METdataio/issues/new/choose), [METviewer](https://github.com/dtcenter/METviewer/issues/new/choose), [METexpress](https://github.com/dtcenter/METexpress/issues/new/choose), [METcalcpy](https://github.com/dtcenter/METcalcpy/issues/new/choose), [METplotpy](https://github.com/dtcenter/METplotpy/issues/new/choose)
No impacts.

## Enhancement Checklist ##
See the [METplus Workflow](https://metplus.readthedocs.io/en/latest/Contributors_Guide/github_workflow.html) for details.
- [ ] Complete the issue definition above, including the **Time Estimate** and **Funding Source**.
- [ ] Fork this repository or create a branch of **develop**.
Branch name: `feature_<Issue Number>_<Description>`
- [ ] Complete the development and test your changes.
- [ ] Add/update log messages for easier debugging.
- [ ] Add/update unit tests.
- [ ] Add/update documentation.
- [ ] Push local changes to GitHub.
- [ ] Submit a pull request to merge into **develop**.
Pull request: `feature <Issue Number> <Description>`
- [ ] Define the pull request metadata, as permissions allow.
Select: **Reviewer(s)** and **Development** issue
Select: **Milestone** as the next official version
Select: **MET-X.Y.Z Development** project for development toward the next official release
- [ ] Iterate until the reviewer(s) accept and merge your changes.
- [ ] Delete your fork or branch.
- [ ] Close this issue.

**Comment by DanielAdriaansen** [comment]
Closed by #3039
