### ISSUE TITLE
Add probability-matched mean computation to Ensemble-Stat

### ISSUE THREAD

**Issue by dwfncar** [dtcenter/MET#422]
Bill Kuo presented a talk about probability matched ensemble means at the DTC staff meeting on 7/10/14.  Seems like it&#39;d be a reasonable extension to Ensemble-Stat when computing ensemble means.  Would need to distinguish between precip and other fields.  For precip, only do probability matching for values > 0. 
<i>[MET-422] created by johnhg</i>

**Comment by jprestop** [comment]
As @TaraJensen mentioned in a previous comment, this is out of the scope of MET at this time.  We want to limit the amount of post-processing included in MET.  The SRW (Short Range Weather) application may be using it and able to produce it.  If this functionality is desired we could check in with the folks that work on the SRW application.
