### ISSUE TITLE
Consider adding centered Anomaly Correlation to the output of MET.

### ISSUE THREAD

**Issue by dwfncar** [dtcenter/MET#619]
This is a request from Dave Ahijevych which came in through met-help:
<br/>
   <a href="https://rt.rap.ucar.edu/rt/Ticket/Display.html?id=77170">https://rt.rap.ucar.edu/rt/Ticket/Display.html?id=77170</a>
<br/>

<br/>
I copied his original email below.  Suggest that we meet with Dave to clarify and see how this relates to the binned AC values that NCEP computes...
<br/>

<br/>
There&#39;s a statistic called anomaly correlation coefficient and there are a
<br/>
couple ways to calculate it. One is "centered" and one is "uncentered" .
<br/>
I&#39;m intestered in the "centered" one because that is what NCEP uses.  It is
<br/>
also used in Krishnamurti et al (Eqn. 7).   The Wilks textbook has them
<br/>
both and so does Jolliffe and Stephenson (2012).
<br/>

<br/>
In MET, right now it only has the "uncentered" version.  In other words it
<br/>
does not remove the average deviation from climatology as the "centered"
<br/>
version does. Willks explains how they are different and so does Jolliffe
<br/>
and Stephenson (2012).
<br/>

<br/>
Any possibility of adding the "centered" version?
<br/>
By the way, I think Beth Ebert&#39;s web page has it slightly wrong. But I&#39;ve
<br/>
already told her. :)
<i>[MET-619] created by johnhg</i>

**Comment by JohnHalleyGotway** [comment]
Completed by #1399
