### ISSUE TITLE
profile MET code and look for time & memory bottlenecks

### ISSUE THREAD

**Issue by davidfillmore** [dtcenter/MET#775]
Turn on code profiling to get a sense of where in the code the speed or memory bottlenecks are.  Examples could be allocating and re-allocating memory repeatedly, repeated unnecessary range checking in buffers, reading data several times, inefficient algorithms (mode is bad for this one) ... others? 
<i>[MET-775] created by bullock</i>

**Comment by JohnHalleyGotway** [comment]
During a telecon with NOAA/MDL, John Wagner offered that we can use their Grid-Stat use case to profile the code and look for bottlenecks.  They use many, many masking regions and it runs pretty slowly.  So this would be a good thing test for debugging.
